// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dlxyz/SubioHub/ent/commissionrule"
)

// CommissionRule is the model entity for the CommissionRule schema.
type CommissionRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Rule name
	Name string `json:"name,omitempty"`
	// Rule status
	Status string `json:"status,omitempty"`
	// Split calculation mode
	CalcMode string `json:"calc_mode,omitempty"`
	// Target rate for channel partners
	ChannelPartnerTargetRate float64 `json:"channel_partner_target_rate,omitempty"`
	// Target rate for agents
	AgentTargetRate float64 `json:"agent_target_rate,omitempty"`
	// Target rate for distributors
	DistributorTargetRate float64 `json:"distributor_target_rate,omitempty"`
	// Settlement freeze window in hours
	FreezeHours int `json:"freeze_hours,omitempty"`
	// Settlement mode
	SettlementMode string `json:"settlement_mode,omitempty"`
	// Scope type: global / channel_partner / agent / distributor
	ScopeType string `json:"scope_type,omitempty"`
	// Scope object ID
	ScopeID *int64 `json:"scope_id,omitempty"`
	// Rule priority
	Priority int `json:"priority,omitempty"`
	// Effective time
	EffectiveAt *time.Time `json:"effective_at,omitempty"`
	// Expired time
	ExpiredAt *time.Time `json:"expired_at,omitempty"`
	// Extended rule config
	ConfigJSON   map[string]interface{} `json:"config_json,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CommissionRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case commissionrule.FieldConfigJSON:
			values[i] = new([]byte)
		case commissionrule.FieldChannelPartnerTargetRate, commissionrule.FieldAgentTargetRate, commissionrule.FieldDistributorTargetRate:
			values[i] = new(sql.NullFloat64)
		case commissionrule.FieldID, commissionrule.FieldFreezeHours, commissionrule.FieldScopeID, commissionrule.FieldPriority:
			values[i] = new(sql.NullInt64)
		case commissionrule.FieldName, commissionrule.FieldStatus, commissionrule.FieldCalcMode, commissionrule.FieldSettlementMode, commissionrule.FieldScopeType:
			values[i] = new(sql.NullString)
		case commissionrule.FieldCreatedAt, commissionrule.FieldUpdatedAt, commissionrule.FieldEffectiveAt, commissionrule.FieldExpiredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CommissionRule fields.
func (_m *CommissionRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case commissionrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case commissionrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case commissionrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case commissionrule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case commissionrule.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case commissionrule.FieldCalcMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field calc_mode", values[i])
			} else if value.Valid {
				_m.CalcMode = value.String
			}
		case commissionrule.FieldChannelPartnerTargetRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_partner_target_rate", values[i])
			} else if value.Valid {
				_m.ChannelPartnerTargetRate = value.Float64
			}
		case commissionrule.FieldAgentTargetRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field agent_target_rate", values[i])
			} else if value.Valid {
				_m.AgentTargetRate = value.Float64
			}
		case commissionrule.FieldDistributorTargetRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field distributor_target_rate", values[i])
			} else if value.Valid {
				_m.DistributorTargetRate = value.Float64
			}
		case commissionrule.FieldFreezeHours:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field freeze_hours", values[i])
			} else if value.Valid {
				_m.FreezeHours = int(value.Int64)
			}
		case commissionrule.FieldSettlementMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field settlement_mode", values[i])
			} else if value.Valid {
				_m.SettlementMode = value.String
			}
		case commissionrule.FieldScopeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_type", values[i])
			} else if value.Valid {
				_m.ScopeType = value.String
			}
		case commissionrule.FieldScopeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field scope_id", values[i])
			} else if value.Valid {
				_m.ScopeID = new(int64)
				*_m.ScopeID = value.Int64
			}
		case commissionrule.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case commissionrule.FieldEffectiveAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field effective_at", values[i])
			} else if value.Valid {
				_m.EffectiveAt = new(time.Time)
				*_m.EffectiveAt = value.Time
			}
		case commissionrule.FieldExpiredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expired_at", values[i])
			} else if value.Valid {
				_m.ExpiredAt = new(time.Time)
				*_m.ExpiredAt = value.Time
			}
		case commissionrule.FieldConfigJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ConfigJSON); err != nil {
					return fmt.Errorf("unmarshal field config_json: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CommissionRule.
// This includes values selected through modifiers, order, etc.
func (_m *CommissionRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CommissionRule.
// Note that you need to call CommissionRule.Unwrap() before calling this method if this CommissionRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CommissionRule) Update() *CommissionRuleUpdateOne {
	return NewCommissionRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CommissionRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CommissionRule) Unwrap() *CommissionRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CommissionRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CommissionRule) String() string {
	var builder strings.Builder
	builder.WriteString("CommissionRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("calc_mode=")
	builder.WriteString(_m.CalcMode)
	builder.WriteString(", ")
	builder.WriteString("channel_partner_target_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelPartnerTargetRate))
	builder.WriteString(", ")
	builder.WriteString("agent_target_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.AgentTargetRate))
	builder.WriteString(", ")
	builder.WriteString("distributor_target_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.DistributorTargetRate))
	builder.WriteString(", ")
	builder.WriteString("freeze_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.FreezeHours))
	builder.WriteString(", ")
	builder.WriteString("settlement_mode=")
	builder.WriteString(_m.SettlementMode)
	builder.WriteString(", ")
	builder.WriteString("scope_type=")
	builder.WriteString(_m.ScopeType)
	builder.WriteString(", ")
	if v := _m.ScopeID; v != nil {
		builder.WriteString("scope_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	if v := _m.EffectiveAt; v != nil {
		builder.WriteString("effective_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiredAt; v != nil {
		builder.WriteString("expired_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("config_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfigJSON))
	builder.WriteByte(')')
	return builder.String()
}

// CommissionRules is a parsable slice of CommissionRule.
type CommissionRules []*CommissionRule
