// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dlxyz/SubioHub/ent/commissionlog"
	"github.com/dlxyz/SubioHub/ent/paymentorder"
	"github.com/dlxyz/SubioHub/ent/predicate"
	"github.com/dlxyz/SubioHub/ent/user"
)

// CommissionLogUpdate is the builder for updating CommissionLog entities.
type CommissionLogUpdate struct {
	config
	hooks    []Hook
	mutation *CommissionLogMutation
}

// Where appends a list predicates to the CommissionLogUpdate builder.
func (_u *CommissionLogUpdate) Where(ps ...predicate.CommissionLog) *CommissionLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommissionLogUpdate) SetUpdatedAt(v time.Time) *CommissionLogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CommissionLogUpdate) SetUserID(v int64) *CommissionLogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CommissionLogUpdate) SetNillableUserID(v *int64) *CommissionLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetInviteeID sets the "invitee_id" field.
func (_u *CommissionLogUpdate) SetInviteeID(v int64) *CommissionLogUpdate {
	_u.mutation.SetInviteeID(v)
	return _u
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_u *CommissionLogUpdate) SetNillableInviteeID(v *int64) *CommissionLogUpdate {
	if v != nil {
		_u.SetInviteeID(*v)
	}
	return _u
}

// ClearInviteeID clears the value of the "invitee_id" field.
func (_u *CommissionLogUpdate) ClearInviteeID() *CommissionLogUpdate {
	_u.mutation.ClearInviteeID()
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *CommissionLogUpdate) SetOrderID(v int64) *CommissionLogUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *CommissionLogUpdate) SetNillableOrderID(v *int64) *CommissionLogUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *CommissionLogUpdate) ClearOrderID() *CommissionLogUpdate {
	_u.mutation.ClearOrderID()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *CommissionLogUpdate) SetAmount(v float64) *CommissionLogUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *CommissionLogUpdate) SetNillableAmount(v *float64) *CommissionLogUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *CommissionLogUpdate) AddAmount(v float64) *CommissionLogUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CommissionLogUpdate) SetStatus(v string) *CommissionLogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CommissionLogUpdate) SetNillableStatus(v *string) *CommissionLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *CommissionLogUpdate) SetReason(v string) *CommissionLogUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *CommissionLogUpdate) SetNillableReason(v *string) *CommissionLogUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CommissionLogUpdate) SetUser(v *User) *CommissionLogUpdate {
	return _u.SetUserID(v.ID)
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_u *CommissionLogUpdate) SetInvitee(v *User) *CommissionLogUpdate {
	return _u.SetInviteeID(v.ID)
}

// SetPaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID.
func (_u *CommissionLogUpdate) SetPaymentOrderID(id int64) *CommissionLogUpdate {
	_u.mutation.SetPaymentOrderID(id)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID if the given value is not nil.
func (_u *CommissionLogUpdate) SetNillablePaymentOrderID(id *int64) *CommissionLogUpdate {
	if id != nil {
		_u = _u.SetPaymentOrderID(*id)
	}
	return _u
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (_u *CommissionLogUpdate) SetPaymentOrder(v *PaymentOrder) *CommissionLogUpdate {
	return _u.SetPaymentOrderID(v.ID)
}

// Mutation returns the CommissionLogMutation object of the builder.
func (_u *CommissionLogUpdate) Mutation() *CommissionLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CommissionLogUpdate) ClearUser() *CommissionLogUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearInvitee clears the "invitee" edge to the User entity.
func (_u *CommissionLogUpdate) ClearInvitee() *CommissionLogUpdate {
	_u.mutation.ClearInvitee()
	return _u
}

// ClearPaymentOrder clears the "payment_order" edge to the PaymentOrder entity.
func (_u *CommissionLogUpdate) ClearPaymentOrder() *CommissionLogUpdate {
	_u.mutation.ClearPaymentOrder()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommissionLogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommissionLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommissionLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommissionLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CommissionLogUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := commissionlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommissionLogUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := commissionlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CommissionLog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := commissionlog.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "CommissionLog.reason": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CommissionLog.user"`)
	}
	return nil
}

func (_u *CommissionLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(commissionlog.Table, commissionlog.Columns, sqlgraph.NewFieldSpec(commissionlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(commissionlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(commissionlog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(commissionlog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(commissionlog.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(commissionlog.FieldReason, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionlog.UserTable,
			Columns: []string{commissionlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionlog.UserTable,
			Columns: []string{commissionlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InviteeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commissionlog.InviteeTable,
			Columns: []string{commissionlog.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commissionlog.InviteeTable,
			Columns: []string{commissionlog.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commissionlog.PaymentOrderTable,
			Columns: []string{commissionlog.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commissionlog.PaymentOrderTable,
			Columns: []string{commissionlog.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commissionlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommissionLogUpdateOne is the builder for updating a single CommissionLog entity.
type CommissionLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommissionLogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommissionLogUpdateOne) SetUpdatedAt(v time.Time) *CommissionLogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CommissionLogUpdateOne) SetUserID(v int64) *CommissionLogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CommissionLogUpdateOne) SetNillableUserID(v *int64) *CommissionLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetInviteeID sets the "invitee_id" field.
func (_u *CommissionLogUpdateOne) SetInviteeID(v int64) *CommissionLogUpdateOne {
	_u.mutation.SetInviteeID(v)
	return _u
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_u *CommissionLogUpdateOne) SetNillableInviteeID(v *int64) *CommissionLogUpdateOne {
	if v != nil {
		_u.SetInviteeID(*v)
	}
	return _u
}

// ClearInviteeID clears the value of the "invitee_id" field.
func (_u *CommissionLogUpdateOne) ClearInviteeID() *CommissionLogUpdateOne {
	_u.mutation.ClearInviteeID()
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *CommissionLogUpdateOne) SetOrderID(v int64) *CommissionLogUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *CommissionLogUpdateOne) SetNillableOrderID(v *int64) *CommissionLogUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *CommissionLogUpdateOne) ClearOrderID() *CommissionLogUpdateOne {
	_u.mutation.ClearOrderID()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *CommissionLogUpdateOne) SetAmount(v float64) *CommissionLogUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *CommissionLogUpdateOne) SetNillableAmount(v *float64) *CommissionLogUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *CommissionLogUpdateOne) AddAmount(v float64) *CommissionLogUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CommissionLogUpdateOne) SetStatus(v string) *CommissionLogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CommissionLogUpdateOne) SetNillableStatus(v *string) *CommissionLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *CommissionLogUpdateOne) SetReason(v string) *CommissionLogUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *CommissionLogUpdateOne) SetNillableReason(v *string) *CommissionLogUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CommissionLogUpdateOne) SetUser(v *User) *CommissionLogUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_u *CommissionLogUpdateOne) SetInvitee(v *User) *CommissionLogUpdateOne {
	return _u.SetInviteeID(v.ID)
}

// SetPaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID.
func (_u *CommissionLogUpdateOne) SetPaymentOrderID(id int64) *CommissionLogUpdateOne {
	_u.mutation.SetPaymentOrderID(id)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID if the given value is not nil.
func (_u *CommissionLogUpdateOne) SetNillablePaymentOrderID(id *int64) *CommissionLogUpdateOne {
	if id != nil {
		_u = _u.SetPaymentOrderID(*id)
	}
	return _u
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (_u *CommissionLogUpdateOne) SetPaymentOrder(v *PaymentOrder) *CommissionLogUpdateOne {
	return _u.SetPaymentOrderID(v.ID)
}

// Mutation returns the CommissionLogMutation object of the builder.
func (_u *CommissionLogUpdateOne) Mutation() *CommissionLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CommissionLogUpdateOne) ClearUser() *CommissionLogUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearInvitee clears the "invitee" edge to the User entity.
func (_u *CommissionLogUpdateOne) ClearInvitee() *CommissionLogUpdateOne {
	_u.mutation.ClearInvitee()
	return _u
}

// ClearPaymentOrder clears the "payment_order" edge to the PaymentOrder entity.
func (_u *CommissionLogUpdateOne) ClearPaymentOrder() *CommissionLogUpdateOne {
	_u.mutation.ClearPaymentOrder()
	return _u
}

// Where appends a list predicates to the CommissionLogUpdate builder.
func (_u *CommissionLogUpdateOne) Where(ps ...predicate.CommissionLog) *CommissionLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommissionLogUpdateOne) Select(field string, fields ...string) *CommissionLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CommissionLog entity.
func (_u *CommissionLogUpdateOne) Save(ctx context.Context) (*CommissionLog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommissionLogUpdateOne) SaveX(ctx context.Context) *CommissionLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommissionLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommissionLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CommissionLogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := commissionlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommissionLogUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := commissionlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CommissionLog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := commissionlog.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "CommissionLog.reason": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CommissionLog.user"`)
	}
	return nil
}

func (_u *CommissionLogUpdateOne) sqlSave(ctx context.Context) (_node *CommissionLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(commissionlog.Table, commissionlog.Columns, sqlgraph.NewFieldSpec(commissionlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CommissionLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commissionlog.FieldID)
		for _, f := range fields {
			if !commissionlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != commissionlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(commissionlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(commissionlog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(commissionlog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(commissionlog.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(commissionlog.FieldReason, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionlog.UserTable,
			Columns: []string{commissionlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionlog.UserTable,
			Columns: []string{commissionlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InviteeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commissionlog.InviteeTable,
			Columns: []string{commissionlog.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commissionlog.InviteeTable,
			Columns: []string{commissionlog.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commissionlog.PaymentOrderTable,
			Columns: []string{commissionlog.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commissionlog.PaymentOrderTable,
			Columns: []string{commissionlog.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CommissionLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commissionlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
