// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dlxyz/SubioHub/ent/commissionrule"
	"github.com/dlxyz/SubioHub/ent/commissionsplitlog"
	"github.com/dlxyz/SubioHub/ent/paymentorder"
	"github.com/dlxyz/SubioHub/ent/user"
)

// CommissionSplitLog is the model entity for the CommissionSplitLog schema.
type CommissionSplitLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 关联订单 ID
	OrderID *int64 `json:"order_id,omitempty"`
	// 消费用户 ID
	ConsumerUserID int64 `json:"consumer_user_id,omitempty"`
	// 实际收益人用户 ID
	BeneficiaryUserID int64 `json:"beneficiary_user_id,omitempty"`
	// 收益人角色：admin/agent/distributor/user
	BeneficiaryRole string `json:"beneficiary_role,omitempty"`
	// 关系链中的代理用户 ID
	AgentUserID *int64 `json:"agent_user_id,omitempty"`
	// 关系链中的分销用户 ID
	DistributorUserID *int64 `json:"distributor_user_id,omitempty"`
	// 分润层级，1=直接收益，2=上级补差
	Level int `json:"level,omitempty"`
	// 分润计算模式：diff=补差法，additive=叠加法
	CalcMode string `json:"calc_mode,omitempty"`
	// 分润基数
	BaseAmount float64 `json:"base_amount,omitempty"`
	// 该层目标比例
	TargetRate float64 `json:"target_rate,omitempty"`
	// 下层已占比例，补差法时用于计算差额
	ParentRate float64 `json:"parent_rate,omitempty"`
	// 最终分润金额
	CommissionAmount float64 `json:"commission_amount,omitempty"`
	// 分润状态：pending / settled / transferred / reversed / cancelled
	Status string `json:"status,omitempty"`
	// 命中的分润规则 ID
	RuleID *int64 `json:"rule_id,omitempty"`
	// 结算时间
	SettledAt *time.Time `json:"settled_at,omitempty"`
	// 关系快照，避免后续关系调整影响历史分润
	RelationSnapshot map[string]interface{} `json:"relation_snapshot,omitempty"`
	// 分润备注
	Remark *string `json:"remark,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CommissionSplitLogQuery when eager-loading is set.
	Edges        CommissionSplitLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CommissionSplitLogEdges holds the relations/edges for other nodes in the graph.
type CommissionSplitLogEdges struct {
	// PaymentOrder holds the value of the payment_order edge.
	PaymentOrder *PaymentOrder `json:"payment_order,omitempty"`
	// ConsumerUser holds the value of the consumer_user edge.
	ConsumerUser *User `json:"consumer_user,omitempty"`
	// BeneficiaryUser holds the value of the beneficiary_user edge.
	BeneficiaryUser *User `json:"beneficiary_user,omitempty"`
	// AgentUser holds the value of the agent_user edge.
	AgentUser *User `json:"agent_user,omitempty"`
	// DistributorUser holds the value of the distributor_user edge.
	DistributorUser *User `json:"distributor_user,omitempty"`
	// CommissionRule holds the value of the commission_rule edge.
	CommissionRule *CommissionRule `json:"commission_rule,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// PaymentOrderOrErr returns the PaymentOrder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CommissionSplitLogEdges) PaymentOrderOrErr() (*PaymentOrder, error) {
	if e.PaymentOrder != nil {
		return e.PaymentOrder, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: paymentorder.Label}
	}
	return nil, &NotLoadedError{edge: "payment_order"}
}

// ConsumerUserOrErr returns the ConsumerUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CommissionSplitLogEdges) ConsumerUserOrErr() (*User, error) {
	if e.ConsumerUser != nil {
		return e.ConsumerUser, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "consumer_user"}
}

// BeneficiaryUserOrErr returns the BeneficiaryUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CommissionSplitLogEdges) BeneficiaryUserOrErr() (*User, error) {
	if e.BeneficiaryUser != nil {
		return e.BeneficiaryUser, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "beneficiary_user"}
}

// AgentUserOrErr returns the AgentUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CommissionSplitLogEdges) AgentUserOrErr() (*User, error) {
	if e.AgentUser != nil {
		return e.AgentUser, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "agent_user"}
}

// DistributorUserOrErr returns the DistributorUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CommissionSplitLogEdges) DistributorUserOrErr() (*User, error) {
	if e.DistributorUser != nil {
		return e.DistributorUser, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "distributor_user"}
}

// CommissionRuleOrErr returns the CommissionRule value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CommissionSplitLogEdges) CommissionRuleOrErr() (*CommissionRule, error) {
	if e.CommissionRule != nil {
		return e.CommissionRule, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: commissionrule.Label}
	}
	return nil, &NotLoadedError{edge: "commission_rule"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CommissionSplitLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case commissionsplitlog.FieldRelationSnapshot:
			values[i] = new([]byte)
		case commissionsplitlog.FieldBaseAmount, commissionsplitlog.FieldTargetRate, commissionsplitlog.FieldParentRate, commissionsplitlog.FieldCommissionAmount:
			values[i] = new(sql.NullFloat64)
		case commissionsplitlog.FieldID, commissionsplitlog.FieldOrderID, commissionsplitlog.FieldConsumerUserID, commissionsplitlog.FieldBeneficiaryUserID, commissionsplitlog.FieldAgentUserID, commissionsplitlog.FieldDistributorUserID, commissionsplitlog.FieldLevel, commissionsplitlog.FieldRuleID:
			values[i] = new(sql.NullInt64)
		case commissionsplitlog.FieldBeneficiaryRole, commissionsplitlog.FieldCalcMode, commissionsplitlog.FieldStatus, commissionsplitlog.FieldRemark:
			values[i] = new(sql.NullString)
		case commissionsplitlog.FieldCreatedAt, commissionsplitlog.FieldUpdatedAt, commissionsplitlog.FieldSettledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CommissionSplitLog fields.
func (_m *CommissionSplitLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case commissionsplitlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case commissionsplitlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case commissionsplitlog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case commissionsplitlog.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = new(int64)
				*_m.OrderID = value.Int64
			}
		case commissionsplitlog.FieldConsumerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consumer_user_id", values[i])
			} else if value.Valid {
				_m.ConsumerUserID = value.Int64
			}
		case commissionsplitlog.FieldBeneficiaryUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field beneficiary_user_id", values[i])
			} else if value.Valid {
				_m.BeneficiaryUserID = value.Int64
			}
		case commissionsplitlog.FieldBeneficiaryRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field beneficiary_role", values[i])
			} else if value.Valid {
				_m.BeneficiaryRole = value.String
			}
		case commissionsplitlog.FieldAgentUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field agent_user_id", values[i])
			} else if value.Valid {
				_m.AgentUserID = new(int64)
				*_m.AgentUserID = value.Int64
			}
		case commissionsplitlog.FieldDistributorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field distributor_user_id", values[i])
			} else if value.Valid {
				_m.DistributorUserID = new(int64)
				*_m.DistributorUserID = value.Int64
			}
		case commissionsplitlog.FieldLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				_m.Level = int(value.Int64)
			}
		case commissionsplitlog.FieldCalcMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field calc_mode", values[i])
			} else if value.Valid {
				_m.CalcMode = value.String
			}
		case commissionsplitlog.FieldBaseAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field base_amount", values[i])
			} else if value.Valid {
				_m.BaseAmount = value.Float64
			}
		case commissionsplitlog.FieldTargetRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field target_rate", values[i])
			} else if value.Valid {
				_m.TargetRate = value.Float64
			}
		case commissionsplitlog.FieldParentRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_rate", values[i])
			} else if value.Valid {
				_m.ParentRate = value.Float64
			}
		case commissionsplitlog.FieldCommissionAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field commission_amount", values[i])
			} else if value.Valid {
				_m.CommissionAmount = value.Float64
			}
		case commissionsplitlog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case commissionsplitlog.FieldRuleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rule_id", values[i])
			} else if value.Valid {
				_m.RuleID = new(int64)
				*_m.RuleID = value.Int64
			}
		case commissionsplitlog.FieldSettledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field settled_at", values[i])
			} else if value.Valid {
				_m.SettledAt = new(time.Time)
				*_m.SettledAt = value.Time
			}
		case commissionsplitlog.FieldRelationSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field relation_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RelationSnapshot); err != nil {
					return fmt.Errorf("unmarshal field relation_snapshot: %w", err)
				}
			}
		case commissionsplitlog.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = new(string)
				*_m.Remark = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CommissionSplitLog.
// This includes values selected through modifiers, order, etc.
func (_m *CommissionSplitLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPaymentOrder queries the "payment_order" edge of the CommissionSplitLog entity.
func (_m *CommissionSplitLog) QueryPaymentOrder() *PaymentOrderQuery {
	return NewCommissionSplitLogClient(_m.config).QueryPaymentOrder(_m)
}

// QueryConsumerUser queries the "consumer_user" edge of the CommissionSplitLog entity.
func (_m *CommissionSplitLog) QueryConsumerUser() *UserQuery {
	return NewCommissionSplitLogClient(_m.config).QueryConsumerUser(_m)
}

// QueryBeneficiaryUser queries the "beneficiary_user" edge of the CommissionSplitLog entity.
func (_m *CommissionSplitLog) QueryBeneficiaryUser() *UserQuery {
	return NewCommissionSplitLogClient(_m.config).QueryBeneficiaryUser(_m)
}

// QueryAgentUser queries the "agent_user" edge of the CommissionSplitLog entity.
func (_m *CommissionSplitLog) QueryAgentUser() *UserQuery {
	return NewCommissionSplitLogClient(_m.config).QueryAgentUser(_m)
}

// QueryDistributorUser queries the "distributor_user" edge of the CommissionSplitLog entity.
func (_m *CommissionSplitLog) QueryDistributorUser() *UserQuery {
	return NewCommissionSplitLogClient(_m.config).QueryDistributorUser(_m)
}

// QueryCommissionRule queries the "commission_rule" edge of the CommissionSplitLog entity.
func (_m *CommissionSplitLog) QueryCommissionRule() *CommissionRuleQuery {
	return NewCommissionSplitLogClient(_m.config).QueryCommissionRule(_m)
}

// Update returns a builder for updating this CommissionSplitLog.
// Note that you need to call CommissionSplitLog.Unwrap() before calling this method if this CommissionSplitLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CommissionSplitLog) Update() *CommissionSplitLogUpdateOne {
	return NewCommissionSplitLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CommissionSplitLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CommissionSplitLog) Unwrap() *CommissionSplitLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CommissionSplitLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CommissionSplitLog) String() string {
	var builder strings.Builder
	builder.WriteString("CommissionSplitLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.OrderID; v != nil {
		builder.WriteString("order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("consumer_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsumerUserID))
	builder.WriteString(", ")
	builder.WriteString("beneficiary_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BeneficiaryUserID))
	builder.WriteString(", ")
	builder.WriteString("beneficiary_role=")
	builder.WriteString(_m.BeneficiaryRole)
	builder.WriteString(", ")
	if v := _m.AgentUserID; v != nil {
		builder.WriteString("agent_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DistributorUserID; v != nil {
		builder.WriteString("distributor_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("level=")
	builder.WriteString(fmt.Sprintf("%v", _m.Level))
	builder.WriteString(", ")
	builder.WriteString("calc_mode=")
	builder.WriteString(_m.CalcMode)
	builder.WriteString(", ")
	builder.WriteString("base_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaseAmount))
	builder.WriteString(", ")
	builder.WriteString("target_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetRate))
	builder.WriteString(", ")
	builder.WriteString("parent_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentRate))
	builder.WriteString(", ")
	builder.WriteString("commission_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommissionAmount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.RuleID; v != nil {
		builder.WriteString("rule_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SettledAt; v != nil {
		builder.WriteString("settled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("relation_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.RelationSnapshot))
	builder.WriteString(", ")
	if v := _m.Remark; v != nil {
		builder.WriteString("remark=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// CommissionSplitLogs is a parsable slice of CommissionSplitLog.
type CommissionSplitLogs []*CommissionSplitLog
