// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dlxyz/SubioHub/ent/commissionrule"
	"github.com/dlxyz/SubioHub/ent/predicate"
)

// CommissionRuleUpdate is the builder for updating CommissionRule entities.
type CommissionRuleUpdate struct {
	config
	hooks    []Hook
	mutation *CommissionRuleMutation
}

// Where appends a list predicates to the CommissionRuleUpdate builder.
func (_u *CommissionRuleUpdate) Where(ps ...predicate.CommissionRule) *CommissionRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommissionRuleUpdate) SetUpdatedAt(v time.Time) *CommissionRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CommissionRuleUpdate) SetName(v string) *CommissionRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CommissionRuleUpdate) SetNillableName(v *string) *CommissionRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CommissionRuleUpdate) SetStatus(v string) *CommissionRuleUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CommissionRuleUpdate) SetNillableStatus(v *string) *CommissionRuleUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCalcMode sets the "calc_mode" field.
func (_u *CommissionRuleUpdate) SetCalcMode(v string) *CommissionRuleUpdate {
	_u.mutation.SetCalcMode(v)
	return _u
}

// SetNillableCalcMode sets the "calc_mode" field if the given value is not nil.
func (_u *CommissionRuleUpdate) SetNillableCalcMode(v *string) *CommissionRuleUpdate {
	if v != nil {
		_u.SetCalcMode(*v)
	}
	return _u
}

// SetChannelPartnerTargetRate sets the "channel_partner_target_rate" field.
func (_u *CommissionRuleUpdate) SetChannelPartnerTargetRate(v float64) *CommissionRuleUpdate {
	_u.mutation.ResetChannelPartnerTargetRate()
	_u.mutation.SetChannelPartnerTargetRate(v)
	return _u
}

// SetNillableChannelPartnerTargetRate sets the "channel_partner_target_rate" field if the given value is not nil.
func (_u *CommissionRuleUpdate) SetNillableChannelPartnerTargetRate(v *float64) *CommissionRuleUpdate {
	if v != nil {
		_u.SetChannelPartnerTargetRate(*v)
	}
	return _u
}

// AddChannelPartnerTargetRate adds value to the "channel_partner_target_rate" field.
func (_u *CommissionRuleUpdate) AddChannelPartnerTargetRate(v float64) *CommissionRuleUpdate {
	_u.mutation.AddChannelPartnerTargetRate(v)
	return _u
}

// SetAgentTargetRate sets the "agent_target_rate" field.
func (_u *CommissionRuleUpdate) SetAgentTargetRate(v float64) *CommissionRuleUpdate {
	_u.mutation.ResetAgentTargetRate()
	_u.mutation.SetAgentTargetRate(v)
	return _u
}

// SetNillableAgentTargetRate sets the "agent_target_rate" field if the given value is not nil.
func (_u *CommissionRuleUpdate) SetNillableAgentTargetRate(v *float64) *CommissionRuleUpdate {
	if v != nil {
		_u.SetAgentTargetRate(*v)
	}
	return _u
}

// AddAgentTargetRate adds value to the "agent_target_rate" field.
func (_u *CommissionRuleUpdate) AddAgentTargetRate(v float64) *CommissionRuleUpdate {
	_u.mutation.AddAgentTargetRate(v)
	return _u
}

// SetDistributorTargetRate sets the "distributor_target_rate" field.
func (_u *CommissionRuleUpdate) SetDistributorTargetRate(v float64) *CommissionRuleUpdate {
	_u.mutation.ResetDistributorTargetRate()
	_u.mutation.SetDistributorTargetRate(v)
	return _u
}

// SetNillableDistributorTargetRate sets the "distributor_target_rate" field if the given value is not nil.
func (_u *CommissionRuleUpdate) SetNillableDistributorTargetRate(v *float64) *CommissionRuleUpdate {
	if v != nil {
		_u.SetDistributorTargetRate(*v)
	}
	return _u
}

// AddDistributorTargetRate adds value to the "distributor_target_rate" field.
func (_u *CommissionRuleUpdate) AddDistributorTargetRate(v float64) *CommissionRuleUpdate {
	_u.mutation.AddDistributorTargetRate(v)
	return _u
}

// SetFreezeHours sets the "freeze_hours" field.
func (_u *CommissionRuleUpdate) SetFreezeHours(v int) *CommissionRuleUpdate {
	_u.mutation.ResetFreezeHours()
	_u.mutation.SetFreezeHours(v)
	return _u
}

// SetNillableFreezeHours sets the "freeze_hours" field if the given value is not nil.
func (_u *CommissionRuleUpdate) SetNillableFreezeHours(v *int) *CommissionRuleUpdate {
	if v != nil {
		_u.SetFreezeHours(*v)
	}
	return _u
}

// AddFreezeHours adds value to the "freeze_hours" field.
func (_u *CommissionRuleUpdate) AddFreezeHours(v int) *CommissionRuleUpdate {
	_u.mutation.AddFreezeHours(v)
	return _u
}

// SetSettlementMode sets the "settlement_mode" field.
func (_u *CommissionRuleUpdate) SetSettlementMode(v string) *CommissionRuleUpdate {
	_u.mutation.SetSettlementMode(v)
	return _u
}

// SetNillableSettlementMode sets the "settlement_mode" field if the given value is not nil.
func (_u *CommissionRuleUpdate) SetNillableSettlementMode(v *string) *CommissionRuleUpdate {
	if v != nil {
		_u.SetSettlementMode(*v)
	}
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *CommissionRuleUpdate) SetScopeType(v string) *CommissionRuleUpdate {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *CommissionRuleUpdate) SetNillableScopeType(v *string) *CommissionRuleUpdate {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *CommissionRuleUpdate) SetScopeID(v int64) *CommissionRuleUpdate {
	_u.mutation.ResetScopeID()
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *CommissionRuleUpdate) SetNillableScopeID(v *int64) *CommissionRuleUpdate {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// AddScopeID adds value to the "scope_id" field.
func (_u *CommissionRuleUpdate) AddScopeID(v int64) *CommissionRuleUpdate {
	_u.mutation.AddScopeID(v)
	return _u
}

// ClearScopeID clears the value of the "scope_id" field.
func (_u *CommissionRuleUpdate) ClearScopeID() *CommissionRuleUpdate {
	_u.mutation.ClearScopeID()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *CommissionRuleUpdate) SetPriority(v int) *CommissionRuleUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *CommissionRuleUpdate) SetNillablePriority(v *int) *CommissionRuleUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *CommissionRuleUpdate) AddPriority(v int) *CommissionRuleUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetEffectiveAt sets the "effective_at" field.
func (_u *CommissionRuleUpdate) SetEffectiveAt(v time.Time) *CommissionRuleUpdate {
	_u.mutation.SetEffectiveAt(v)
	return _u
}

// SetNillableEffectiveAt sets the "effective_at" field if the given value is not nil.
func (_u *CommissionRuleUpdate) SetNillableEffectiveAt(v *time.Time) *CommissionRuleUpdate {
	if v != nil {
		_u.SetEffectiveAt(*v)
	}
	return _u
}

// ClearEffectiveAt clears the value of the "effective_at" field.
func (_u *CommissionRuleUpdate) ClearEffectiveAt() *CommissionRuleUpdate {
	_u.mutation.ClearEffectiveAt()
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *CommissionRuleUpdate) SetExpiredAt(v time.Time) *CommissionRuleUpdate {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *CommissionRuleUpdate) SetNillableExpiredAt(v *time.Time) *CommissionRuleUpdate {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *CommissionRuleUpdate) ClearExpiredAt() *CommissionRuleUpdate {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetConfigJSON sets the "config_json" field.
func (_u *CommissionRuleUpdate) SetConfigJSON(v map[string]interface{}) *CommissionRuleUpdate {
	_u.mutation.SetConfigJSON(v)
	return _u
}

// ClearConfigJSON clears the value of the "config_json" field.
func (_u *CommissionRuleUpdate) ClearConfigJSON() *CommissionRuleUpdate {
	_u.mutation.ClearConfigJSON()
	return _u
}

// Mutation returns the CommissionRuleMutation object of the builder.
func (_u *CommissionRuleUpdate) Mutation() *CommissionRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommissionRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommissionRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommissionRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommissionRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CommissionRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := commissionrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommissionRuleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := commissionrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CommissionRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := commissionrule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CommissionRule.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CalcMode(); ok {
		if err := commissionrule.CalcModeValidator(v); err != nil {
			return &ValidationError{Name: "calc_mode", err: fmt.Errorf(`ent: validator failed for field "CommissionRule.calc_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SettlementMode(); ok {
		if err := commissionrule.SettlementModeValidator(v); err != nil {
			return &ValidationError{Name: "settlement_mode", err: fmt.Errorf(`ent: validator failed for field "CommissionRule.settlement_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := commissionrule.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "CommissionRule.scope_type": %w`, err)}
		}
	}
	return nil
}

func (_u *CommissionRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(commissionrule.Table, commissionrule.Columns, sqlgraph.NewFieldSpec(commissionrule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(commissionrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(commissionrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(commissionrule.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CalcMode(); ok {
		_spec.SetField(commissionrule.FieldCalcMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelPartnerTargetRate(); ok {
		_spec.SetField(commissionrule.FieldChannelPartnerTargetRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedChannelPartnerTargetRate(); ok {
		_spec.AddField(commissionrule.FieldChannelPartnerTargetRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AgentTargetRate(); ok {
		_spec.SetField(commissionrule.FieldAgentTargetRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAgentTargetRate(); ok {
		_spec.AddField(commissionrule.FieldAgentTargetRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DistributorTargetRate(); ok {
		_spec.SetField(commissionrule.FieldDistributorTargetRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDistributorTargetRate(); ok {
		_spec.AddField(commissionrule.FieldDistributorTargetRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FreezeHours(); ok {
		_spec.SetField(commissionrule.FieldFreezeHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFreezeHours(); ok {
		_spec.AddField(commissionrule.FieldFreezeHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SettlementMode(); ok {
		_spec.SetField(commissionrule.FieldSettlementMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(commissionrule.FieldScopeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(commissionrule.FieldScopeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedScopeID(); ok {
		_spec.AddField(commissionrule.FieldScopeID, field.TypeInt64, value)
	}
	if _u.mutation.ScopeIDCleared() {
		_spec.ClearField(commissionrule.FieldScopeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(commissionrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(commissionrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EffectiveAt(); ok {
		_spec.SetField(commissionrule.FieldEffectiveAt, field.TypeTime, value)
	}
	if _u.mutation.EffectiveAtCleared() {
		_spec.ClearField(commissionrule.FieldEffectiveAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(commissionrule.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(commissionrule.FieldExpiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConfigJSON(); ok {
		_spec.SetField(commissionrule.FieldConfigJSON, field.TypeJSON, value)
	}
	if _u.mutation.ConfigJSONCleared() {
		_spec.ClearField(commissionrule.FieldConfigJSON, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commissionrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommissionRuleUpdateOne is the builder for updating a single CommissionRule entity.
type CommissionRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommissionRuleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommissionRuleUpdateOne) SetUpdatedAt(v time.Time) *CommissionRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CommissionRuleUpdateOne) SetName(v string) *CommissionRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CommissionRuleUpdateOne) SetNillableName(v *string) *CommissionRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CommissionRuleUpdateOne) SetStatus(v string) *CommissionRuleUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CommissionRuleUpdateOne) SetNillableStatus(v *string) *CommissionRuleUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCalcMode sets the "calc_mode" field.
func (_u *CommissionRuleUpdateOne) SetCalcMode(v string) *CommissionRuleUpdateOne {
	_u.mutation.SetCalcMode(v)
	return _u
}

// SetNillableCalcMode sets the "calc_mode" field if the given value is not nil.
func (_u *CommissionRuleUpdateOne) SetNillableCalcMode(v *string) *CommissionRuleUpdateOne {
	if v != nil {
		_u.SetCalcMode(*v)
	}
	return _u
}

// SetChannelPartnerTargetRate sets the "channel_partner_target_rate" field.
func (_u *CommissionRuleUpdateOne) SetChannelPartnerTargetRate(v float64) *CommissionRuleUpdateOne {
	_u.mutation.ResetChannelPartnerTargetRate()
	_u.mutation.SetChannelPartnerTargetRate(v)
	return _u
}

// SetNillableChannelPartnerTargetRate sets the "channel_partner_target_rate" field if the given value is not nil.
func (_u *CommissionRuleUpdateOne) SetNillableChannelPartnerTargetRate(v *float64) *CommissionRuleUpdateOne {
	if v != nil {
		_u.SetChannelPartnerTargetRate(*v)
	}
	return _u
}

// AddChannelPartnerTargetRate adds value to the "channel_partner_target_rate" field.
func (_u *CommissionRuleUpdateOne) AddChannelPartnerTargetRate(v float64) *CommissionRuleUpdateOne {
	_u.mutation.AddChannelPartnerTargetRate(v)
	return _u
}

// SetAgentTargetRate sets the "agent_target_rate" field.
func (_u *CommissionRuleUpdateOne) SetAgentTargetRate(v float64) *CommissionRuleUpdateOne {
	_u.mutation.ResetAgentTargetRate()
	_u.mutation.SetAgentTargetRate(v)
	return _u
}

// SetNillableAgentTargetRate sets the "agent_target_rate" field if the given value is not nil.
func (_u *CommissionRuleUpdateOne) SetNillableAgentTargetRate(v *float64) *CommissionRuleUpdateOne {
	if v != nil {
		_u.SetAgentTargetRate(*v)
	}
	return _u
}

// AddAgentTargetRate adds value to the "agent_target_rate" field.
func (_u *CommissionRuleUpdateOne) AddAgentTargetRate(v float64) *CommissionRuleUpdateOne {
	_u.mutation.AddAgentTargetRate(v)
	return _u
}

// SetDistributorTargetRate sets the "distributor_target_rate" field.
func (_u *CommissionRuleUpdateOne) SetDistributorTargetRate(v float64) *CommissionRuleUpdateOne {
	_u.mutation.ResetDistributorTargetRate()
	_u.mutation.SetDistributorTargetRate(v)
	return _u
}

// SetNillableDistributorTargetRate sets the "distributor_target_rate" field if the given value is not nil.
func (_u *CommissionRuleUpdateOne) SetNillableDistributorTargetRate(v *float64) *CommissionRuleUpdateOne {
	if v != nil {
		_u.SetDistributorTargetRate(*v)
	}
	return _u
}

// AddDistributorTargetRate adds value to the "distributor_target_rate" field.
func (_u *CommissionRuleUpdateOne) AddDistributorTargetRate(v float64) *CommissionRuleUpdateOne {
	_u.mutation.AddDistributorTargetRate(v)
	return _u
}

// SetFreezeHours sets the "freeze_hours" field.
func (_u *CommissionRuleUpdateOne) SetFreezeHours(v int) *CommissionRuleUpdateOne {
	_u.mutation.ResetFreezeHours()
	_u.mutation.SetFreezeHours(v)
	return _u
}

// SetNillableFreezeHours sets the "freeze_hours" field if the given value is not nil.
func (_u *CommissionRuleUpdateOne) SetNillableFreezeHours(v *int) *CommissionRuleUpdateOne {
	if v != nil {
		_u.SetFreezeHours(*v)
	}
	return _u
}

// AddFreezeHours adds value to the "freeze_hours" field.
func (_u *CommissionRuleUpdateOne) AddFreezeHours(v int) *CommissionRuleUpdateOne {
	_u.mutation.AddFreezeHours(v)
	return _u
}

// SetSettlementMode sets the "settlement_mode" field.
func (_u *CommissionRuleUpdateOne) SetSettlementMode(v string) *CommissionRuleUpdateOne {
	_u.mutation.SetSettlementMode(v)
	return _u
}

// SetNillableSettlementMode sets the "settlement_mode" field if the given value is not nil.
func (_u *CommissionRuleUpdateOne) SetNillableSettlementMode(v *string) *CommissionRuleUpdateOne {
	if v != nil {
		_u.SetSettlementMode(*v)
	}
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *CommissionRuleUpdateOne) SetScopeType(v string) *CommissionRuleUpdateOne {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *CommissionRuleUpdateOne) SetNillableScopeType(v *string) *CommissionRuleUpdateOne {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *CommissionRuleUpdateOne) SetScopeID(v int64) *CommissionRuleUpdateOne {
	_u.mutation.ResetScopeID()
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *CommissionRuleUpdateOne) SetNillableScopeID(v *int64) *CommissionRuleUpdateOne {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// AddScopeID adds value to the "scope_id" field.
func (_u *CommissionRuleUpdateOne) AddScopeID(v int64) *CommissionRuleUpdateOne {
	_u.mutation.AddScopeID(v)
	return _u
}

// ClearScopeID clears the value of the "scope_id" field.
func (_u *CommissionRuleUpdateOne) ClearScopeID() *CommissionRuleUpdateOne {
	_u.mutation.ClearScopeID()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *CommissionRuleUpdateOne) SetPriority(v int) *CommissionRuleUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *CommissionRuleUpdateOne) SetNillablePriority(v *int) *CommissionRuleUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *CommissionRuleUpdateOne) AddPriority(v int) *CommissionRuleUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetEffectiveAt sets the "effective_at" field.
func (_u *CommissionRuleUpdateOne) SetEffectiveAt(v time.Time) *CommissionRuleUpdateOne {
	_u.mutation.SetEffectiveAt(v)
	return _u
}

// SetNillableEffectiveAt sets the "effective_at" field if the given value is not nil.
func (_u *CommissionRuleUpdateOne) SetNillableEffectiveAt(v *time.Time) *CommissionRuleUpdateOne {
	if v != nil {
		_u.SetEffectiveAt(*v)
	}
	return _u
}

// ClearEffectiveAt clears the value of the "effective_at" field.
func (_u *CommissionRuleUpdateOne) ClearEffectiveAt() *CommissionRuleUpdateOne {
	_u.mutation.ClearEffectiveAt()
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *CommissionRuleUpdateOne) SetExpiredAt(v time.Time) *CommissionRuleUpdateOne {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *CommissionRuleUpdateOne) SetNillableExpiredAt(v *time.Time) *CommissionRuleUpdateOne {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *CommissionRuleUpdateOne) ClearExpiredAt() *CommissionRuleUpdateOne {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetConfigJSON sets the "config_json" field.
func (_u *CommissionRuleUpdateOne) SetConfigJSON(v map[string]interface{}) *CommissionRuleUpdateOne {
	_u.mutation.SetConfigJSON(v)
	return _u
}

// ClearConfigJSON clears the value of the "config_json" field.
func (_u *CommissionRuleUpdateOne) ClearConfigJSON() *CommissionRuleUpdateOne {
	_u.mutation.ClearConfigJSON()
	return _u
}

// Mutation returns the CommissionRuleMutation object of the builder.
func (_u *CommissionRuleUpdateOne) Mutation() *CommissionRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the CommissionRuleUpdate builder.
func (_u *CommissionRuleUpdateOne) Where(ps ...predicate.CommissionRule) *CommissionRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommissionRuleUpdateOne) Select(field string, fields ...string) *CommissionRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CommissionRule entity.
func (_u *CommissionRuleUpdateOne) Save(ctx context.Context) (*CommissionRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommissionRuleUpdateOne) SaveX(ctx context.Context) *CommissionRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommissionRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommissionRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CommissionRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := commissionrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommissionRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := commissionrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CommissionRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := commissionrule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CommissionRule.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CalcMode(); ok {
		if err := commissionrule.CalcModeValidator(v); err != nil {
			return &ValidationError{Name: "calc_mode", err: fmt.Errorf(`ent: validator failed for field "CommissionRule.calc_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SettlementMode(); ok {
		if err := commissionrule.SettlementModeValidator(v); err != nil {
			return &ValidationError{Name: "settlement_mode", err: fmt.Errorf(`ent: validator failed for field "CommissionRule.settlement_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := commissionrule.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "CommissionRule.scope_type": %w`, err)}
		}
	}
	return nil
}

func (_u *CommissionRuleUpdateOne) sqlSave(ctx context.Context) (_node *CommissionRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(commissionrule.Table, commissionrule.Columns, sqlgraph.NewFieldSpec(commissionrule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CommissionRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commissionrule.FieldID)
		for _, f := range fields {
			if !commissionrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != commissionrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(commissionrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(commissionrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(commissionrule.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CalcMode(); ok {
		_spec.SetField(commissionrule.FieldCalcMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelPartnerTargetRate(); ok {
		_spec.SetField(commissionrule.FieldChannelPartnerTargetRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedChannelPartnerTargetRate(); ok {
		_spec.AddField(commissionrule.FieldChannelPartnerTargetRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AgentTargetRate(); ok {
		_spec.SetField(commissionrule.FieldAgentTargetRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAgentTargetRate(); ok {
		_spec.AddField(commissionrule.FieldAgentTargetRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DistributorTargetRate(); ok {
		_spec.SetField(commissionrule.FieldDistributorTargetRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDistributorTargetRate(); ok {
		_spec.AddField(commissionrule.FieldDistributorTargetRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FreezeHours(); ok {
		_spec.SetField(commissionrule.FieldFreezeHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFreezeHours(); ok {
		_spec.AddField(commissionrule.FieldFreezeHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SettlementMode(); ok {
		_spec.SetField(commissionrule.FieldSettlementMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(commissionrule.FieldScopeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(commissionrule.FieldScopeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedScopeID(); ok {
		_spec.AddField(commissionrule.FieldScopeID, field.TypeInt64, value)
	}
	if _u.mutation.ScopeIDCleared() {
		_spec.ClearField(commissionrule.FieldScopeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(commissionrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(commissionrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EffectiveAt(); ok {
		_spec.SetField(commissionrule.FieldEffectiveAt, field.TypeTime, value)
	}
	if _u.mutation.EffectiveAtCleared() {
		_spec.ClearField(commissionrule.FieldEffectiveAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(commissionrule.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(commissionrule.FieldExpiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConfigJSON(); ok {
		_spec.SetField(commissionrule.FieldConfigJSON, field.TypeJSON, value)
	}
	if _u.mutation.ConfigJSONCleared() {
		_spec.ClearField(commissionrule.FieldConfigJSON, field.TypeJSON)
	}
	_node = &CommissionRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commissionrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
