// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dlxyz/SubioHub/ent/commissionlog"
	"github.com/dlxyz/SubioHub/ent/paymentorder"
	"github.com/dlxyz/SubioHub/ent/user"
)

// CommissionLogCreate is the builder for creating a CommissionLog entity.
type CommissionLogCreate struct {
	config
	mutation *CommissionLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CommissionLogCreate) SetCreatedAt(v time.Time) *CommissionLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CommissionLogCreate) SetNillableCreatedAt(v *time.Time) *CommissionLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CommissionLogCreate) SetUpdatedAt(v time.Time) *CommissionLogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CommissionLogCreate) SetNillableUpdatedAt(v *time.Time) *CommissionLogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CommissionLogCreate) SetUserID(v int64) *CommissionLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetInviteeID sets the "invitee_id" field.
func (_c *CommissionLogCreate) SetInviteeID(v int64) *CommissionLogCreate {
	_c.mutation.SetInviteeID(v)
	return _c
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_c *CommissionLogCreate) SetNillableInviteeID(v *int64) *CommissionLogCreate {
	if v != nil {
		_c.SetInviteeID(*v)
	}
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *CommissionLogCreate) SetOrderID(v int64) *CommissionLogCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_c *CommissionLogCreate) SetNillableOrderID(v *int64) *CommissionLogCreate {
	if v != nil {
		_c.SetOrderID(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *CommissionLogCreate) SetAmount(v float64) *CommissionLogCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CommissionLogCreate) SetStatus(v string) *CommissionLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CommissionLogCreate) SetNillableStatus(v *string) *CommissionLogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *CommissionLogCreate) SetReason(v string) *CommissionLogCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *CommissionLogCreate) SetNillableReason(v *string) *CommissionLogCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CommissionLogCreate) SetUser(v *User) *CommissionLogCreate {
	return _c.SetUserID(v.ID)
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_c *CommissionLogCreate) SetInvitee(v *User) *CommissionLogCreate {
	return _c.SetInviteeID(v.ID)
}

// SetPaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID.
func (_c *CommissionLogCreate) SetPaymentOrderID(id int64) *CommissionLogCreate {
	_c.mutation.SetPaymentOrderID(id)
	return _c
}

// SetNillablePaymentOrderID sets the "payment_order" edge to the PaymentOrder entity by ID if the given value is not nil.
func (_c *CommissionLogCreate) SetNillablePaymentOrderID(id *int64) *CommissionLogCreate {
	if id != nil {
		_c = _c.SetPaymentOrderID(*id)
	}
	return _c
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (_c *CommissionLogCreate) SetPaymentOrder(v *PaymentOrder) *CommissionLogCreate {
	return _c.SetPaymentOrderID(v.ID)
}

// Mutation returns the CommissionLogMutation object of the builder.
func (_c *CommissionLogCreate) Mutation() *CommissionLogMutation {
	return _c.mutation
}

// Save creates the CommissionLog in the database.
func (_c *CommissionLogCreate) Save(ctx context.Context) (*CommissionLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CommissionLogCreate) SaveX(ctx context.Context) *CommissionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommissionLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommissionLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CommissionLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := commissionlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := commissionlog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := commissionlog.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Reason(); !ok {
		v := commissionlog.DefaultReason
		_c.mutation.SetReason(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CommissionLogCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CommissionLog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CommissionLog.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CommissionLog.user_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "CommissionLog.amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CommissionLog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := commissionlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CommissionLog.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "CommissionLog.reason"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := commissionlog.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "CommissionLog.reason": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CommissionLog.user"`)}
	}
	return nil
}

func (_c *CommissionLogCreate) sqlSave(ctx context.Context) (*CommissionLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CommissionLogCreate) createSpec() (*CommissionLog, *sqlgraph.CreateSpec) {
	var (
		_node = &CommissionLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(commissionlog.Table, sqlgraph.NewFieldSpec(commissionlog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(commissionlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(commissionlog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(commissionlog.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(commissionlog.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(commissionlog.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionlog.UserTable,
			Columns: []string{commissionlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commissionlog.InviteeTable,
			Columns: []string{commissionlog.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InviteeID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commissionlog.PaymentOrderTable,
			Columns: []string{commissionlog.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CommissionLog.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CommissionLogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CommissionLogCreate) OnConflict(opts ...sql.ConflictOption) *CommissionLogUpsertOne {
	_c.conflict = opts
	return &CommissionLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CommissionLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CommissionLogCreate) OnConflictColumns(columns ...string) *CommissionLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CommissionLogUpsertOne{
		create: _c,
	}
}

type (
	// CommissionLogUpsertOne is the builder for "upsert"-ing
	//  one CommissionLog node.
	CommissionLogUpsertOne struct {
		create *CommissionLogCreate
	}

	// CommissionLogUpsert is the "OnConflict" setter.
	CommissionLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CommissionLogUpsert) SetUpdatedAt(v time.Time) *CommissionLogUpsert {
	u.Set(commissionlog.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CommissionLogUpsert) UpdateUpdatedAt() *CommissionLogUpsert {
	u.SetExcluded(commissionlog.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *CommissionLogUpsert) SetUserID(v int64) *CommissionLogUpsert {
	u.Set(commissionlog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CommissionLogUpsert) UpdateUserID() *CommissionLogUpsert {
	u.SetExcluded(commissionlog.FieldUserID)
	return u
}

// SetInviteeID sets the "invitee_id" field.
func (u *CommissionLogUpsert) SetInviteeID(v int64) *CommissionLogUpsert {
	u.Set(commissionlog.FieldInviteeID, v)
	return u
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *CommissionLogUpsert) UpdateInviteeID() *CommissionLogUpsert {
	u.SetExcluded(commissionlog.FieldInviteeID)
	return u
}

// ClearInviteeID clears the value of the "invitee_id" field.
func (u *CommissionLogUpsert) ClearInviteeID() *CommissionLogUpsert {
	u.SetNull(commissionlog.FieldInviteeID)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *CommissionLogUpsert) SetOrderID(v int64) *CommissionLogUpsert {
	u.Set(commissionlog.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *CommissionLogUpsert) UpdateOrderID() *CommissionLogUpsert {
	u.SetExcluded(commissionlog.FieldOrderID)
	return u
}

// ClearOrderID clears the value of the "order_id" field.
func (u *CommissionLogUpsert) ClearOrderID() *CommissionLogUpsert {
	u.SetNull(commissionlog.FieldOrderID)
	return u
}

// SetAmount sets the "amount" field.
func (u *CommissionLogUpsert) SetAmount(v float64) *CommissionLogUpsert {
	u.Set(commissionlog.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CommissionLogUpsert) UpdateAmount() *CommissionLogUpsert {
	u.SetExcluded(commissionlog.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *CommissionLogUpsert) AddAmount(v float64) *CommissionLogUpsert {
	u.Add(commissionlog.FieldAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *CommissionLogUpsert) SetStatus(v string) *CommissionLogUpsert {
	u.Set(commissionlog.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CommissionLogUpsert) UpdateStatus() *CommissionLogUpsert {
	u.SetExcluded(commissionlog.FieldStatus)
	return u
}

// SetReason sets the "reason" field.
func (u *CommissionLogUpsert) SetReason(v string) *CommissionLogUpsert {
	u.Set(commissionlog.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *CommissionLogUpsert) UpdateReason() *CommissionLogUpsert {
	u.SetExcluded(commissionlog.FieldReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CommissionLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CommissionLogUpsertOne) UpdateNewValues() *CommissionLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(commissionlog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CommissionLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CommissionLogUpsertOne) Ignore() *CommissionLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CommissionLogUpsertOne) DoNothing() *CommissionLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CommissionLogCreate.OnConflict
// documentation for more info.
func (u *CommissionLogUpsertOne) Update(set func(*CommissionLogUpsert)) *CommissionLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CommissionLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CommissionLogUpsertOne) SetUpdatedAt(v time.Time) *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CommissionLogUpsertOne) UpdateUpdatedAt() *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *CommissionLogUpsertOne) SetUserID(v int64) *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CommissionLogUpsertOne) UpdateUserID() *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.UpdateUserID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *CommissionLogUpsertOne) SetInviteeID(v int64) *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.SetInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *CommissionLogUpsertOne) UpdateInviteeID() *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.UpdateInviteeID()
	})
}

// ClearInviteeID clears the value of the "invitee_id" field.
func (u *CommissionLogUpsertOne) ClearInviteeID() *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.ClearInviteeID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *CommissionLogUpsertOne) SetOrderID(v int64) *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *CommissionLogUpsertOne) UpdateOrderID() *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *CommissionLogUpsertOne) ClearOrderID() *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.ClearOrderID()
	})
}

// SetAmount sets the "amount" field.
func (u *CommissionLogUpsertOne) SetAmount(v float64) *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *CommissionLogUpsertOne) AddAmount(v float64) *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CommissionLogUpsertOne) UpdateAmount() *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *CommissionLogUpsertOne) SetStatus(v string) *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CommissionLogUpsertOne) UpdateStatus() *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.UpdateStatus()
	})
}

// SetReason sets the "reason" field.
func (u *CommissionLogUpsertOne) SetReason(v string) *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *CommissionLogUpsertOne) UpdateReason() *CommissionLogUpsertOne {
	return u.Update(func(s *CommissionLogUpsert) {
		s.UpdateReason()
	})
}

// Exec executes the query.
func (u *CommissionLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CommissionLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CommissionLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CommissionLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CommissionLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CommissionLogCreateBulk is the builder for creating many CommissionLog entities in bulk.
type CommissionLogCreateBulk struct {
	config
	err      error
	builders []*CommissionLogCreate
	conflict []sql.ConflictOption
}

// Save creates the CommissionLog entities in the database.
func (_c *CommissionLogCreateBulk) Save(ctx context.Context) ([]*CommissionLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CommissionLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommissionLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CommissionLogCreateBulk) SaveX(ctx context.Context) []*CommissionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommissionLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommissionLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CommissionLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CommissionLogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CommissionLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *CommissionLogUpsertBulk {
	_c.conflict = opts
	return &CommissionLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CommissionLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CommissionLogCreateBulk) OnConflictColumns(columns ...string) *CommissionLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CommissionLogUpsertBulk{
		create: _c,
	}
}

// CommissionLogUpsertBulk is the builder for "upsert"-ing
// a bulk of CommissionLog nodes.
type CommissionLogUpsertBulk struct {
	create *CommissionLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CommissionLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CommissionLogUpsertBulk) UpdateNewValues() *CommissionLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(commissionlog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CommissionLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CommissionLogUpsertBulk) Ignore() *CommissionLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CommissionLogUpsertBulk) DoNothing() *CommissionLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CommissionLogCreateBulk.OnConflict
// documentation for more info.
func (u *CommissionLogUpsertBulk) Update(set func(*CommissionLogUpsert)) *CommissionLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CommissionLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CommissionLogUpsertBulk) SetUpdatedAt(v time.Time) *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CommissionLogUpsertBulk) UpdateUpdatedAt() *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *CommissionLogUpsertBulk) SetUserID(v int64) *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CommissionLogUpsertBulk) UpdateUserID() *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.UpdateUserID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *CommissionLogUpsertBulk) SetInviteeID(v int64) *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.SetInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *CommissionLogUpsertBulk) UpdateInviteeID() *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.UpdateInviteeID()
	})
}

// ClearInviteeID clears the value of the "invitee_id" field.
func (u *CommissionLogUpsertBulk) ClearInviteeID() *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.ClearInviteeID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *CommissionLogUpsertBulk) SetOrderID(v int64) *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *CommissionLogUpsertBulk) UpdateOrderID() *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *CommissionLogUpsertBulk) ClearOrderID() *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.ClearOrderID()
	})
}

// SetAmount sets the "amount" field.
func (u *CommissionLogUpsertBulk) SetAmount(v float64) *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *CommissionLogUpsertBulk) AddAmount(v float64) *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CommissionLogUpsertBulk) UpdateAmount() *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *CommissionLogUpsertBulk) SetStatus(v string) *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CommissionLogUpsertBulk) UpdateStatus() *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.UpdateStatus()
	})
}

// SetReason sets the "reason" field.
func (u *CommissionLogUpsertBulk) SetReason(v string) *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *CommissionLogUpsertBulk) UpdateReason() *CommissionLogUpsertBulk {
	return u.Update(func(s *CommissionLogUpsert) {
		s.UpdateReason()
	})
}

// Exec executes the query.
func (u *CommissionLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CommissionLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CommissionLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CommissionLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
