// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dlxyz/SubioHub/ent/commissionrule"
	"github.com/dlxyz/SubioHub/ent/commissionsplitlog"
	"github.com/dlxyz/SubioHub/ent/paymentorder"
	"github.com/dlxyz/SubioHub/ent/predicate"
	"github.com/dlxyz/SubioHub/ent/user"
)

// CommissionSplitLogQuery is the builder for querying CommissionSplitLog entities.
type CommissionSplitLogQuery struct {
	config
	ctx                    *QueryContext
	order                  []commissionsplitlog.OrderOption
	inters                 []Interceptor
	predicates             []predicate.CommissionSplitLog
	withPaymentOrder       *PaymentOrderQuery
	withConsumerUser       *UserQuery
	withBeneficiaryUser    *UserQuery
	withChannelPartnerUser *UserQuery
	withAgentUser          *UserQuery
	withDistributorUser    *UserQuery
	withCommissionRule     *CommissionRuleQuery
	modifiers              []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CommissionSplitLogQuery builder.
func (_q *CommissionSplitLogQuery) Where(ps ...predicate.CommissionSplitLog) *CommissionSplitLogQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CommissionSplitLogQuery) Limit(limit int) *CommissionSplitLogQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CommissionSplitLogQuery) Offset(offset int) *CommissionSplitLogQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CommissionSplitLogQuery) Unique(unique bool) *CommissionSplitLogQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CommissionSplitLogQuery) Order(o ...commissionsplitlog.OrderOption) *CommissionSplitLogQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPaymentOrder chains the current query on the "payment_order" edge.
func (_q *CommissionSplitLogQuery) QueryPaymentOrder() *PaymentOrderQuery {
	query := (&PaymentOrderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionsplitlog.Table, commissionsplitlog.FieldID, selector),
			sqlgraph.To(paymentorder.Table, paymentorder.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, commissionsplitlog.PaymentOrderTable, commissionsplitlog.PaymentOrderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryConsumerUser chains the current query on the "consumer_user" edge.
func (_q *CommissionSplitLogQuery) QueryConsumerUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionsplitlog.Table, commissionsplitlog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, commissionsplitlog.ConsumerUserTable, commissionsplitlog.ConsumerUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBeneficiaryUser chains the current query on the "beneficiary_user" edge.
func (_q *CommissionSplitLogQuery) QueryBeneficiaryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionsplitlog.Table, commissionsplitlog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, commissionsplitlog.BeneficiaryUserTable, commissionsplitlog.BeneficiaryUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChannelPartnerUser chains the current query on the "channel_partner_user" edge.
func (_q *CommissionSplitLogQuery) QueryChannelPartnerUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionsplitlog.Table, commissionsplitlog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, commissionsplitlog.ChannelPartnerUserTable, commissionsplitlog.ChannelPartnerUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAgentUser chains the current query on the "agent_user" edge.
func (_q *CommissionSplitLogQuery) QueryAgentUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionsplitlog.Table, commissionsplitlog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, commissionsplitlog.AgentUserTable, commissionsplitlog.AgentUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDistributorUser chains the current query on the "distributor_user" edge.
func (_q *CommissionSplitLogQuery) QueryDistributorUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionsplitlog.Table, commissionsplitlog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, commissionsplitlog.DistributorUserTable, commissionsplitlog.DistributorUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCommissionRule chains the current query on the "commission_rule" edge.
func (_q *CommissionSplitLogQuery) QueryCommissionRule() *CommissionRuleQuery {
	query := (&CommissionRuleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionsplitlog.Table, commissionsplitlog.FieldID, selector),
			sqlgraph.To(commissionrule.Table, commissionrule.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, commissionsplitlog.CommissionRuleTable, commissionsplitlog.CommissionRuleColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CommissionSplitLog entity from the query.
// Returns a *NotFoundError when no CommissionSplitLog was found.
func (_q *CommissionSplitLogQuery) First(ctx context.Context) (*CommissionSplitLog, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{commissionsplitlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CommissionSplitLogQuery) FirstX(ctx context.Context) *CommissionSplitLog {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CommissionSplitLog ID from the query.
// Returns a *NotFoundError when no CommissionSplitLog ID was found.
func (_q *CommissionSplitLogQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{commissionsplitlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CommissionSplitLogQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CommissionSplitLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CommissionSplitLog entity is found.
// Returns a *NotFoundError when no CommissionSplitLog entities are found.
func (_q *CommissionSplitLogQuery) Only(ctx context.Context) (*CommissionSplitLog, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{commissionsplitlog.Label}
	default:
		return nil, &NotSingularError{commissionsplitlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CommissionSplitLogQuery) OnlyX(ctx context.Context) *CommissionSplitLog {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CommissionSplitLog ID in the query.
// Returns a *NotSingularError when more than one CommissionSplitLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CommissionSplitLogQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{commissionsplitlog.Label}
	default:
		err = &NotSingularError{commissionsplitlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CommissionSplitLogQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CommissionSplitLogs.
func (_q *CommissionSplitLogQuery) All(ctx context.Context) ([]*CommissionSplitLog, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CommissionSplitLog, *CommissionSplitLogQuery]()
	return withInterceptors[[]*CommissionSplitLog](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CommissionSplitLogQuery) AllX(ctx context.Context) []*CommissionSplitLog {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CommissionSplitLog IDs.
func (_q *CommissionSplitLogQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(commissionsplitlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CommissionSplitLogQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CommissionSplitLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CommissionSplitLogQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CommissionSplitLogQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CommissionSplitLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CommissionSplitLogQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CommissionSplitLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CommissionSplitLogQuery) Clone() *CommissionSplitLogQuery {
	if _q == nil {
		return nil
	}
	return &CommissionSplitLogQuery{
		config:                 _q.config,
		ctx:                    _q.ctx.Clone(),
		order:                  append([]commissionsplitlog.OrderOption{}, _q.order...),
		inters:                 append([]Interceptor{}, _q.inters...),
		predicates:             append([]predicate.CommissionSplitLog{}, _q.predicates...),
		withPaymentOrder:       _q.withPaymentOrder.Clone(),
		withConsumerUser:       _q.withConsumerUser.Clone(),
		withBeneficiaryUser:    _q.withBeneficiaryUser.Clone(),
		withChannelPartnerUser: _q.withChannelPartnerUser.Clone(),
		withAgentUser:          _q.withAgentUser.Clone(),
		withDistributorUser:    _q.withDistributorUser.Clone(),
		withCommissionRule:     _q.withCommissionRule.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPaymentOrder tells the query-builder to eager-load the nodes that are connected to
// the "payment_order" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionSplitLogQuery) WithPaymentOrder(opts ...func(*PaymentOrderQuery)) *CommissionSplitLogQuery {
	query := (&PaymentOrderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPaymentOrder = query
	return _q
}

// WithConsumerUser tells the query-builder to eager-load the nodes that are connected to
// the "consumer_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionSplitLogQuery) WithConsumerUser(opts ...func(*UserQuery)) *CommissionSplitLogQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withConsumerUser = query
	return _q
}

// WithBeneficiaryUser tells the query-builder to eager-load the nodes that are connected to
// the "beneficiary_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionSplitLogQuery) WithBeneficiaryUser(opts ...func(*UserQuery)) *CommissionSplitLogQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBeneficiaryUser = query
	return _q
}

// WithChannelPartnerUser tells the query-builder to eager-load the nodes that are connected to
// the "channel_partner_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionSplitLogQuery) WithChannelPartnerUser(opts ...func(*UserQuery)) *CommissionSplitLogQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChannelPartnerUser = query
	return _q
}

// WithAgentUser tells the query-builder to eager-load the nodes that are connected to
// the "agent_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionSplitLogQuery) WithAgentUser(opts ...func(*UserQuery)) *CommissionSplitLogQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAgentUser = query
	return _q
}

// WithDistributorUser tells the query-builder to eager-load the nodes that are connected to
// the "distributor_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionSplitLogQuery) WithDistributorUser(opts ...func(*UserQuery)) *CommissionSplitLogQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDistributorUser = query
	return _q
}

// WithCommissionRule tells the query-builder to eager-load the nodes that are connected to
// the "commission_rule" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionSplitLogQuery) WithCommissionRule(opts ...func(*CommissionRuleQuery)) *CommissionSplitLogQuery {
	query := (&CommissionRuleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCommissionRule = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CommissionSplitLog.Query().
//		GroupBy(commissionsplitlog.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CommissionSplitLogQuery) GroupBy(field string, fields ...string) *CommissionSplitLogGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CommissionSplitLogGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = commissionsplitlog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.CommissionSplitLog.Query().
//		Select(commissionsplitlog.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *CommissionSplitLogQuery) Select(fields ...string) *CommissionSplitLogSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CommissionSplitLogSelect{CommissionSplitLogQuery: _q}
	sbuild.label = commissionsplitlog.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CommissionSplitLogSelect configured with the given aggregations.
func (_q *CommissionSplitLogQuery) Aggregate(fns ...AggregateFunc) *CommissionSplitLogSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CommissionSplitLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !commissionsplitlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CommissionSplitLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CommissionSplitLog, error) {
	var (
		nodes       = []*CommissionSplitLog{}
		_spec       = _q.querySpec()
		loadedTypes = [7]bool{
			_q.withPaymentOrder != nil,
			_q.withConsumerUser != nil,
			_q.withBeneficiaryUser != nil,
			_q.withChannelPartnerUser != nil,
			_q.withAgentUser != nil,
			_q.withDistributorUser != nil,
			_q.withCommissionRule != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CommissionSplitLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CommissionSplitLog{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPaymentOrder; query != nil {
		if err := _q.loadPaymentOrder(ctx, query, nodes, nil,
			func(n *CommissionSplitLog, e *PaymentOrder) { n.Edges.PaymentOrder = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withConsumerUser; query != nil {
		if err := _q.loadConsumerUser(ctx, query, nodes, nil,
			func(n *CommissionSplitLog, e *User) { n.Edges.ConsumerUser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBeneficiaryUser; query != nil {
		if err := _q.loadBeneficiaryUser(ctx, query, nodes, nil,
			func(n *CommissionSplitLog, e *User) { n.Edges.BeneficiaryUser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChannelPartnerUser; query != nil {
		if err := _q.loadChannelPartnerUser(ctx, query, nodes, nil,
			func(n *CommissionSplitLog, e *User) { n.Edges.ChannelPartnerUser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAgentUser; query != nil {
		if err := _q.loadAgentUser(ctx, query, nodes, nil,
			func(n *CommissionSplitLog, e *User) { n.Edges.AgentUser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDistributorUser; query != nil {
		if err := _q.loadDistributorUser(ctx, query, nodes, nil,
			func(n *CommissionSplitLog, e *User) { n.Edges.DistributorUser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCommissionRule; query != nil {
		if err := _q.loadCommissionRule(ctx, query, nodes, nil,
			func(n *CommissionSplitLog, e *CommissionRule) { n.Edges.CommissionRule = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CommissionSplitLogQuery) loadPaymentOrder(ctx context.Context, query *PaymentOrderQuery, nodes []*CommissionSplitLog, init func(*CommissionSplitLog), assign func(*CommissionSplitLog, *PaymentOrder)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionSplitLog)
	for i := range nodes {
		if nodes[i].OrderID == nil {
			continue
		}
		fk := *nodes[i].OrderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(paymentorder.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "order_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CommissionSplitLogQuery) loadConsumerUser(ctx context.Context, query *UserQuery, nodes []*CommissionSplitLog, init func(*CommissionSplitLog), assign func(*CommissionSplitLog, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionSplitLog)
	for i := range nodes {
		fk := nodes[i].ConsumerUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "consumer_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CommissionSplitLogQuery) loadBeneficiaryUser(ctx context.Context, query *UserQuery, nodes []*CommissionSplitLog, init func(*CommissionSplitLog), assign func(*CommissionSplitLog, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionSplitLog)
	for i := range nodes {
		fk := nodes[i].BeneficiaryUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "beneficiary_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CommissionSplitLogQuery) loadChannelPartnerUser(ctx context.Context, query *UserQuery, nodes []*CommissionSplitLog, init func(*CommissionSplitLog), assign func(*CommissionSplitLog, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionSplitLog)
	for i := range nodes {
		if nodes[i].ChannelPartnerUserID == nil {
			continue
		}
		fk := *nodes[i].ChannelPartnerUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "channel_partner_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CommissionSplitLogQuery) loadAgentUser(ctx context.Context, query *UserQuery, nodes []*CommissionSplitLog, init func(*CommissionSplitLog), assign func(*CommissionSplitLog, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionSplitLog)
	for i := range nodes {
		if nodes[i].AgentUserID == nil {
			continue
		}
		fk := *nodes[i].AgentUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "agent_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CommissionSplitLogQuery) loadDistributorUser(ctx context.Context, query *UserQuery, nodes []*CommissionSplitLog, init func(*CommissionSplitLog), assign func(*CommissionSplitLog, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionSplitLog)
	for i := range nodes {
		if nodes[i].DistributorUserID == nil {
			continue
		}
		fk := *nodes[i].DistributorUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "distributor_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CommissionSplitLogQuery) loadCommissionRule(ctx context.Context, query *CommissionRuleQuery, nodes []*CommissionSplitLog, init func(*CommissionSplitLog), assign func(*CommissionSplitLog, *CommissionRule)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionSplitLog)
	for i := range nodes {
		if nodes[i].RuleID == nil {
			continue
		}
		fk := *nodes[i].RuleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(commissionrule.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "rule_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *CommissionSplitLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CommissionSplitLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(commissionsplitlog.Table, commissionsplitlog.Columns, sqlgraph.NewFieldSpec(commissionsplitlog.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commissionsplitlog.FieldID)
		for i := range fields {
			if fields[i] != commissionsplitlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withPaymentOrder != nil {
			_spec.Node.AddColumnOnce(commissionsplitlog.FieldOrderID)
		}
		if _q.withConsumerUser != nil {
			_spec.Node.AddColumnOnce(commissionsplitlog.FieldConsumerUserID)
		}
		if _q.withBeneficiaryUser != nil {
			_spec.Node.AddColumnOnce(commissionsplitlog.FieldBeneficiaryUserID)
		}
		if _q.withChannelPartnerUser != nil {
			_spec.Node.AddColumnOnce(commissionsplitlog.FieldChannelPartnerUserID)
		}
		if _q.withAgentUser != nil {
			_spec.Node.AddColumnOnce(commissionsplitlog.FieldAgentUserID)
		}
		if _q.withDistributorUser != nil {
			_spec.Node.AddColumnOnce(commissionsplitlog.FieldDistributorUserID)
		}
		if _q.withCommissionRule != nil {
			_spec.Node.AddColumnOnce(commissionsplitlog.FieldRuleID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CommissionSplitLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(commissionsplitlog.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = commissionsplitlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *CommissionSplitLogQuery) ForUpdate(opts ...sql.LockOption) *CommissionSplitLogQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *CommissionSplitLogQuery) ForShare(opts ...sql.LockOption) *CommissionSplitLogQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// CommissionSplitLogGroupBy is the group-by builder for CommissionSplitLog entities.
type CommissionSplitLogGroupBy struct {
	selector
	build *CommissionSplitLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CommissionSplitLogGroupBy) Aggregate(fns ...AggregateFunc) *CommissionSplitLogGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CommissionSplitLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommissionSplitLogQuery, *CommissionSplitLogGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CommissionSplitLogGroupBy) sqlScan(ctx context.Context, root *CommissionSplitLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CommissionSplitLogSelect is the builder for selecting fields of CommissionSplitLog entities.
type CommissionSplitLogSelect struct {
	*CommissionSplitLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CommissionSplitLogSelect) Aggregate(fns ...AggregateFunc) *CommissionSplitLogSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CommissionSplitLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommissionSplitLogQuery, *CommissionSplitLogSelect](ctx, _s.CommissionSplitLogQuery, _s, _s.inters, v)
}

func (_s *CommissionSplitLogSelect) sqlScan(ctx context.Context, root *CommissionSplitLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
