// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dlxyz/SubioHub/ent/newspost"
	"github.com/dlxyz/SubioHub/ent/newsposttranslation"
)

// NewsPostCreate is the builder for creating a NewsPost entity.
type NewsPostCreate struct {
	config
	mutation *NewsPostMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSlug sets the "slug" field.
func (_c *NewsPostCreate) SetSlug(v string) *NewsPostCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *NewsPostCreate) SetStatus(v string) *NewsPostCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *NewsPostCreate) SetNillableStatus(v *string) *NewsPostCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDefaultLocale sets the "default_locale" field.
func (_c *NewsPostCreate) SetDefaultLocale(v string) *NewsPostCreate {
	_c.mutation.SetDefaultLocale(v)
	return _c
}

// SetNillableDefaultLocale sets the "default_locale" field if the given value is not nil.
func (_c *NewsPostCreate) SetNillableDefaultLocale(v *string) *NewsPostCreate {
	if v != nil {
		_c.SetDefaultLocale(*v)
	}
	return _c
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_c *NewsPostCreate) SetCoverImageURL(v string) *NewsPostCreate {
	_c.mutation.SetCoverImageURL(v)
	return _c
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_c *NewsPostCreate) SetNillableCoverImageURL(v *string) *NewsPostCreate {
	if v != nil {
		_c.SetCoverImageURL(*v)
	}
	return _c
}

// SetAuthorName sets the "author_name" field.
func (_c *NewsPostCreate) SetAuthorName(v string) *NewsPostCreate {
	_c.mutation.SetAuthorName(v)
	return _c
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_c *NewsPostCreate) SetNillableAuthorName(v *string) *NewsPostCreate {
	if v != nil {
		_c.SetAuthorName(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *NewsPostCreate) SetPublishedAt(v time.Time) *NewsPostCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *NewsPostCreate) SetNillablePublishedAt(v *time.Time) *NewsPostCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *NewsPostCreate) SetCreatedBy(v int64) *NewsPostCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *NewsPostCreate) SetNillableCreatedBy(v *int64) *NewsPostCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *NewsPostCreate) SetUpdatedBy(v int64) *NewsPostCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *NewsPostCreate) SetNillableUpdatedBy(v *int64) *NewsPostCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NewsPostCreate) SetCreatedAt(v time.Time) *NewsPostCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NewsPostCreate) SetNillableCreatedAt(v *time.Time) *NewsPostCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NewsPostCreate) SetUpdatedAt(v time.Time) *NewsPostCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NewsPostCreate) SetNillableUpdatedAt(v *time.Time) *NewsPostCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddTranslationIDs adds the "translations" edge to the NewsPostTranslation entity by IDs.
func (_c *NewsPostCreate) AddTranslationIDs(ids ...int64) *NewsPostCreate {
	_c.mutation.AddTranslationIDs(ids...)
	return _c
}

// AddTranslations adds the "translations" edges to the NewsPostTranslation entity.
func (_c *NewsPostCreate) AddTranslations(v ...*NewsPostTranslation) *NewsPostCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTranslationIDs(ids...)
}

// Mutation returns the NewsPostMutation object of the builder.
func (_c *NewsPostCreate) Mutation() *NewsPostMutation {
	return _c.mutation
}

// Save creates the NewsPost in the database.
func (_c *NewsPostCreate) Save(ctx context.Context) (*NewsPost, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NewsPostCreate) SaveX(ctx context.Context) *NewsPost {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NewsPostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NewsPostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NewsPostCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := newspost.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DefaultLocale(); !ok {
		v := newspost.DefaultDefaultLocale
		_c.mutation.SetDefaultLocale(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := newspost.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := newspost.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NewsPostCreate) check() error {
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "NewsPost.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := newspost.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "NewsPost.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "NewsPost.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := newspost.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "NewsPost.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultLocale(); !ok {
		return &ValidationError{Name: "default_locale", err: errors.New(`ent: missing required field "NewsPost.default_locale"`)}
	}
	if v, ok := _c.mutation.DefaultLocale(); ok {
		if err := newspost.DefaultLocaleValidator(v); err != nil {
			return &ValidationError{Name: "default_locale", err: fmt.Errorf(`ent: validator failed for field "NewsPost.default_locale": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CoverImageURL(); ok {
		if err := newspost.CoverImageURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_image_url", err: fmt.Errorf(`ent: validator failed for field "NewsPost.cover_image_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AuthorName(); ok {
		if err := newspost.AuthorNameValidator(v); err != nil {
			return &ValidationError{Name: "author_name", err: fmt.Errorf(`ent: validator failed for field "NewsPost.author_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NewsPost.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NewsPost.updated_at"`)}
	}
	return nil
}

func (_c *NewsPostCreate) sqlSave(ctx context.Context) (*NewsPost, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NewsPostCreate) createSpec() (*NewsPost, *sqlgraph.CreateSpec) {
	var (
		_node = &NewsPost{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(newspost.Table, sqlgraph.NewFieldSpec(newspost.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(newspost.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(newspost.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DefaultLocale(); ok {
		_spec.SetField(newspost.FieldDefaultLocale, field.TypeString, value)
		_node.DefaultLocale = value
	}
	if value, ok := _c.mutation.CoverImageURL(); ok {
		_spec.SetField(newspost.FieldCoverImageURL, field.TypeString, value)
		_node.CoverImageURL = &value
	}
	if value, ok := _c.mutation.AuthorName(); ok {
		_spec.SetField(newspost.FieldAuthorName, field.TypeString, value)
		_node.AuthorName = &value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(newspost.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(newspost.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(newspost.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(newspost.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(newspost.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TranslationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   newspost.TranslationsTable,
			Columns: []string{newspost.TranslationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(newsposttranslation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NewsPost.Create().
//		SetSlug(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NewsPostUpsert) {
//			SetSlug(v+v).
//		}).
//		Exec(ctx)
func (_c *NewsPostCreate) OnConflict(opts ...sql.ConflictOption) *NewsPostUpsertOne {
	_c.conflict = opts
	return &NewsPostUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NewsPost.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NewsPostCreate) OnConflictColumns(columns ...string) *NewsPostUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NewsPostUpsertOne{
		create: _c,
	}
}

type (
	// NewsPostUpsertOne is the builder for "upsert"-ing
	//  one NewsPost node.
	NewsPostUpsertOne struct {
		create *NewsPostCreate
	}

	// NewsPostUpsert is the "OnConflict" setter.
	NewsPostUpsert struct {
		*sql.UpdateSet
	}
)

// SetSlug sets the "slug" field.
func (u *NewsPostUpsert) SetSlug(v string) *NewsPostUpsert {
	u.Set(newspost.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *NewsPostUpsert) UpdateSlug() *NewsPostUpsert {
	u.SetExcluded(newspost.FieldSlug)
	return u
}

// SetStatus sets the "status" field.
func (u *NewsPostUpsert) SetStatus(v string) *NewsPostUpsert {
	u.Set(newspost.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NewsPostUpsert) UpdateStatus() *NewsPostUpsert {
	u.SetExcluded(newspost.FieldStatus)
	return u
}

// SetDefaultLocale sets the "default_locale" field.
func (u *NewsPostUpsert) SetDefaultLocale(v string) *NewsPostUpsert {
	u.Set(newspost.FieldDefaultLocale, v)
	return u
}

// UpdateDefaultLocale sets the "default_locale" field to the value that was provided on create.
func (u *NewsPostUpsert) UpdateDefaultLocale() *NewsPostUpsert {
	u.SetExcluded(newspost.FieldDefaultLocale)
	return u
}

// SetCoverImageURL sets the "cover_image_url" field.
func (u *NewsPostUpsert) SetCoverImageURL(v string) *NewsPostUpsert {
	u.Set(newspost.FieldCoverImageURL, v)
	return u
}

// UpdateCoverImageURL sets the "cover_image_url" field to the value that was provided on create.
func (u *NewsPostUpsert) UpdateCoverImageURL() *NewsPostUpsert {
	u.SetExcluded(newspost.FieldCoverImageURL)
	return u
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (u *NewsPostUpsert) ClearCoverImageURL() *NewsPostUpsert {
	u.SetNull(newspost.FieldCoverImageURL)
	return u
}

// SetAuthorName sets the "author_name" field.
func (u *NewsPostUpsert) SetAuthorName(v string) *NewsPostUpsert {
	u.Set(newspost.FieldAuthorName, v)
	return u
}

// UpdateAuthorName sets the "author_name" field to the value that was provided on create.
func (u *NewsPostUpsert) UpdateAuthorName() *NewsPostUpsert {
	u.SetExcluded(newspost.FieldAuthorName)
	return u
}

// ClearAuthorName clears the value of the "author_name" field.
func (u *NewsPostUpsert) ClearAuthorName() *NewsPostUpsert {
	u.SetNull(newspost.FieldAuthorName)
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *NewsPostUpsert) SetPublishedAt(v time.Time) *NewsPostUpsert {
	u.Set(newspost.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *NewsPostUpsert) UpdatePublishedAt() *NewsPostUpsert {
	u.SetExcluded(newspost.FieldPublishedAt)
	return u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *NewsPostUpsert) ClearPublishedAt() *NewsPostUpsert {
	u.SetNull(newspost.FieldPublishedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *NewsPostUpsert) SetCreatedBy(v int64) *NewsPostUpsert {
	u.Set(newspost.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *NewsPostUpsert) UpdateCreatedBy() *NewsPostUpsert {
	u.SetExcluded(newspost.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *NewsPostUpsert) AddCreatedBy(v int64) *NewsPostUpsert {
	u.Add(newspost.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *NewsPostUpsert) ClearCreatedBy() *NewsPostUpsert {
	u.SetNull(newspost.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *NewsPostUpsert) SetUpdatedBy(v int64) *NewsPostUpsert {
	u.Set(newspost.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *NewsPostUpsert) UpdateUpdatedBy() *NewsPostUpsert {
	u.SetExcluded(newspost.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *NewsPostUpsert) AddUpdatedBy(v int64) *NewsPostUpsert {
	u.Add(newspost.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *NewsPostUpsert) ClearUpdatedBy() *NewsPostUpsert {
	u.SetNull(newspost.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NewsPostUpsert) SetUpdatedAt(v time.Time) *NewsPostUpsert {
	u.Set(newspost.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NewsPostUpsert) UpdateUpdatedAt() *NewsPostUpsert {
	u.SetExcluded(newspost.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.NewsPost.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NewsPostUpsertOne) UpdateNewValues() *NewsPostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(newspost.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NewsPost.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NewsPostUpsertOne) Ignore() *NewsPostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NewsPostUpsertOne) DoNothing() *NewsPostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NewsPostCreate.OnConflict
// documentation for more info.
func (u *NewsPostUpsertOne) Update(set func(*NewsPostUpsert)) *NewsPostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NewsPostUpsert{UpdateSet: update})
	}))
	return u
}

// SetSlug sets the "slug" field.
func (u *NewsPostUpsertOne) SetSlug(v string) *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *NewsPostUpsertOne) UpdateSlug() *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateSlug()
	})
}

// SetStatus sets the "status" field.
func (u *NewsPostUpsertOne) SetStatus(v string) *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NewsPostUpsertOne) UpdateStatus() *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateStatus()
	})
}

// SetDefaultLocale sets the "default_locale" field.
func (u *NewsPostUpsertOne) SetDefaultLocale(v string) *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetDefaultLocale(v)
	})
}

// UpdateDefaultLocale sets the "default_locale" field to the value that was provided on create.
func (u *NewsPostUpsertOne) UpdateDefaultLocale() *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateDefaultLocale()
	})
}

// SetCoverImageURL sets the "cover_image_url" field.
func (u *NewsPostUpsertOne) SetCoverImageURL(v string) *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetCoverImageURL(v)
	})
}

// UpdateCoverImageURL sets the "cover_image_url" field to the value that was provided on create.
func (u *NewsPostUpsertOne) UpdateCoverImageURL() *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateCoverImageURL()
	})
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (u *NewsPostUpsertOne) ClearCoverImageURL() *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.ClearCoverImageURL()
	})
}

// SetAuthorName sets the "author_name" field.
func (u *NewsPostUpsertOne) SetAuthorName(v string) *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetAuthorName(v)
	})
}

// UpdateAuthorName sets the "author_name" field to the value that was provided on create.
func (u *NewsPostUpsertOne) UpdateAuthorName() *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateAuthorName()
	})
}

// ClearAuthorName clears the value of the "author_name" field.
func (u *NewsPostUpsertOne) ClearAuthorName() *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.ClearAuthorName()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *NewsPostUpsertOne) SetPublishedAt(v time.Time) *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *NewsPostUpsertOne) UpdatePublishedAt() *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *NewsPostUpsertOne) ClearPublishedAt() *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.ClearPublishedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *NewsPostUpsertOne) SetCreatedBy(v int64) *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *NewsPostUpsertOne) AddCreatedBy(v int64) *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *NewsPostUpsertOne) UpdateCreatedBy() *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *NewsPostUpsertOne) ClearCreatedBy() *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *NewsPostUpsertOne) SetUpdatedBy(v int64) *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *NewsPostUpsertOne) AddUpdatedBy(v int64) *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *NewsPostUpsertOne) UpdateUpdatedBy() *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *NewsPostUpsertOne) ClearUpdatedBy() *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NewsPostUpsertOne) SetUpdatedAt(v time.Time) *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NewsPostUpsertOne) UpdateUpdatedAt() *NewsPostUpsertOne {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NewsPostUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NewsPostCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NewsPostUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NewsPostUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NewsPostUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NewsPostCreateBulk is the builder for creating many NewsPost entities in bulk.
type NewsPostCreateBulk struct {
	config
	err      error
	builders []*NewsPostCreate
	conflict []sql.ConflictOption
}

// Save creates the NewsPost entities in the database.
func (_c *NewsPostCreateBulk) Save(ctx context.Context) ([]*NewsPost, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NewsPost, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NewsPostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NewsPostCreateBulk) SaveX(ctx context.Context) []*NewsPost {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NewsPostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NewsPostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NewsPost.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NewsPostUpsert) {
//			SetSlug(v+v).
//		}).
//		Exec(ctx)
func (_c *NewsPostCreateBulk) OnConflict(opts ...sql.ConflictOption) *NewsPostUpsertBulk {
	_c.conflict = opts
	return &NewsPostUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NewsPost.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NewsPostCreateBulk) OnConflictColumns(columns ...string) *NewsPostUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NewsPostUpsertBulk{
		create: _c,
	}
}

// NewsPostUpsertBulk is the builder for "upsert"-ing
// a bulk of NewsPost nodes.
type NewsPostUpsertBulk struct {
	create *NewsPostCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NewsPost.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NewsPostUpsertBulk) UpdateNewValues() *NewsPostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(newspost.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NewsPost.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NewsPostUpsertBulk) Ignore() *NewsPostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NewsPostUpsertBulk) DoNothing() *NewsPostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NewsPostCreateBulk.OnConflict
// documentation for more info.
func (u *NewsPostUpsertBulk) Update(set func(*NewsPostUpsert)) *NewsPostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NewsPostUpsert{UpdateSet: update})
	}))
	return u
}

// SetSlug sets the "slug" field.
func (u *NewsPostUpsertBulk) SetSlug(v string) *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *NewsPostUpsertBulk) UpdateSlug() *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateSlug()
	})
}

// SetStatus sets the "status" field.
func (u *NewsPostUpsertBulk) SetStatus(v string) *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NewsPostUpsertBulk) UpdateStatus() *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateStatus()
	})
}

// SetDefaultLocale sets the "default_locale" field.
func (u *NewsPostUpsertBulk) SetDefaultLocale(v string) *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetDefaultLocale(v)
	})
}

// UpdateDefaultLocale sets the "default_locale" field to the value that was provided on create.
func (u *NewsPostUpsertBulk) UpdateDefaultLocale() *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateDefaultLocale()
	})
}

// SetCoverImageURL sets the "cover_image_url" field.
func (u *NewsPostUpsertBulk) SetCoverImageURL(v string) *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetCoverImageURL(v)
	})
}

// UpdateCoverImageURL sets the "cover_image_url" field to the value that was provided on create.
func (u *NewsPostUpsertBulk) UpdateCoverImageURL() *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateCoverImageURL()
	})
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (u *NewsPostUpsertBulk) ClearCoverImageURL() *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.ClearCoverImageURL()
	})
}

// SetAuthorName sets the "author_name" field.
func (u *NewsPostUpsertBulk) SetAuthorName(v string) *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetAuthorName(v)
	})
}

// UpdateAuthorName sets the "author_name" field to the value that was provided on create.
func (u *NewsPostUpsertBulk) UpdateAuthorName() *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateAuthorName()
	})
}

// ClearAuthorName clears the value of the "author_name" field.
func (u *NewsPostUpsertBulk) ClearAuthorName() *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.ClearAuthorName()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *NewsPostUpsertBulk) SetPublishedAt(v time.Time) *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *NewsPostUpsertBulk) UpdatePublishedAt() *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *NewsPostUpsertBulk) ClearPublishedAt() *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.ClearPublishedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *NewsPostUpsertBulk) SetCreatedBy(v int64) *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *NewsPostUpsertBulk) AddCreatedBy(v int64) *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *NewsPostUpsertBulk) UpdateCreatedBy() *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *NewsPostUpsertBulk) ClearCreatedBy() *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *NewsPostUpsertBulk) SetUpdatedBy(v int64) *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *NewsPostUpsertBulk) AddUpdatedBy(v int64) *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *NewsPostUpsertBulk) UpdateUpdatedBy() *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *NewsPostUpsertBulk) ClearUpdatedBy() *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NewsPostUpsertBulk) SetUpdatedAt(v time.Time) *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NewsPostUpsertBulk) UpdateUpdatedAt() *NewsPostUpsertBulk {
	return u.Update(func(s *NewsPostUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NewsPostUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NewsPostCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NewsPostCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NewsPostUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
