// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dlxyz/SubioHub/ent/newspost"
	"github.com/dlxyz/SubioHub/ent/newsposttranslation"
	"github.com/dlxyz/SubioHub/ent/predicate"
)

// NewsPostQuery is the builder for querying NewsPost entities.
type NewsPostQuery struct {
	config
	ctx              *QueryContext
	order            []newspost.OrderOption
	inters           []Interceptor
	predicates       []predicate.NewsPost
	withTranslations *NewsPostTranslationQuery
	modifiers        []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NewsPostQuery builder.
func (_q *NewsPostQuery) Where(ps ...predicate.NewsPost) *NewsPostQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *NewsPostQuery) Limit(limit int) *NewsPostQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *NewsPostQuery) Offset(offset int) *NewsPostQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *NewsPostQuery) Unique(unique bool) *NewsPostQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *NewsPostQuery) Order(o ...newspost.OrderOption) *NewsPostQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTranslations chains the current query on the "translations" edge.
func (_q *NewsPostQuery) QueryTranslations() *NewsPostTranslationQuery {
	query := (&NewsPostTranslationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(newspost.Table, newspost.FieldID, selector),
			sqlgraph.To(newsposttranslation.Table, newsposttranslation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, newspost.TranslationsTable, newspost.TranslationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first NewsPost entity from the query.
// Returns a *NotFoundError when no NewsPost was found.
func (_q *NewsPostQuery) First(ctx context.Context) (*NewsPost, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{newspost.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *NewsPostQuery) FirstX(ctx context.Context) *NewsPost {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NewsPost ID from the query.
// Returns a *NotFoundError when no NewsPost ID was found.
func (_q *NewsPostQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{newspost.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *NewsPostQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NewsPost entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NewsPost entity is found.
// Returns a *NotFoundError when no NewsPost entities are found.
func (_q *NewsPostQuery) Only(ctx context.Context) (*NewsPost, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{newspost.Label}
	default:
		return nil, &NotSingularError{newspost.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *NewsPostQuery) OnlyX(ctx context.Context) *NewsPost {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NewsPost ID in the query.
// Returns a *NotSingularError when more than one NewsPost ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *NewsPostQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{newspost.Label}
	default:
		err = &NotSingularError{newspost.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *NewsPostQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NewsPosts.
func (_q *NewsPostQuery) All(ctx context.Context) ([]*NewsPost, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NewsPost, *NewsPostQuery]()
	return withInterceptors[[]*NewsPost](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *NewsPostQuery) AllX(ctx context.Context) []*NewsPost {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NewsPost IDs.
func (_q *NewsPostQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(newspost.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *NewsPostQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *NewsPostQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*NewsPostQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *NewsPostQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *NewsPostQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *NewsPostQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NewsPostQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *NewsPostQuery) Clone() *NewsPostQuery {
	if _q == nil {
		return nil
	}
	return &NewsPostQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]newspost.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.NewsPost{}, _q.predicates...),
		withTranslations: _q.withTranslations.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTranslations tells the query-builder to eager-load the nodes that are connected to
// the "translations" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NewsPostQuery) WithTranslations(opts ...func(*NewsPostTranslationQuery)) *NewsPostQuery {
	query := (&NewsPostTranslationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTranslations = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Slug string `json:"slug,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NewsPost.Query().
//		GroupBy(newspost.FieldSlug).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *NewsPostQuery) GroupBy(field string, fields ...string) *NewsPostGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NewsPostGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = newspost.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Slug string `json:"slug,omitempty"`
//	}
//
//	client.NewsPost.Query().
//		Select(newspost.FieldSlug).
//		Scan(ctx, &v)
func (_q *NewsPostQuery) Select(fields ...string) *NewsPostSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &NewsPostSelect{NewsPostQuery: _q}
	sbuild.label = newspost.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NewsPostSelect configured with the given aggregations.
func (_q *NewsPostQuery) Aggregate(fns ...AggregateFunc) *NewsPostSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *NewsPostQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !newspost.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *NewsPostQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NewsPost, error) {
	var (
		nodes       = []*NewsPost{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withTranslations != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NewsPost).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NewsPost{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTranslations; query != nil {
		if err := _q.loadTranslations(ctx, query, nodes,
			func(n *NewsPost) { n.Edges.Translations = []*NewsPostTranslation{} },
			func(n *NewsPost, e *NewsPostTranslation) { n.Edges.Translations = append(n.Edges.Translations, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *NewsPostQuery) loadTranslations(ctx context.Context, query *NewsPostTranslationQuery, nodes []*NewsPost, init func(*NewsPost), assign func(*NewsPost, *NewsPostTranslation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*NewsPost)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(newsposttranslation.FieldNewsPostID)
	}
	query.Where(predicate.NewsPostTranslation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(newspost.TranslationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.NewsPostID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "news_post_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *NewsPostQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *NewsPostQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(newspost.Table, newspost.Columns, sqlgraph.NewFieldSpec(newspost.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, newspost.FieldID)
		for i := range fields {
			if fields[i] != newspost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *NewsPostQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(newspost.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = newspost.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *NewsPostQuery) ForUpdate(opts ...sql.LockOption) *NewsPostQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *NewsPostQuery) ForShare(opts ...sql.LockOption) *NewsPostQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// NewsPostGroupBy is the group-by builder for NewsPost entities.
type NewsPostGroupBy struct {
	selector
	build *NewsPostQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *NewsPostGroupBy) Aggregate(fns ...AggregateFunc) *NewsPostGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *NewsPostGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NewsPostQuery, *NewsPostGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *NewsPostGroupBy) sqlScan(ctx context.Context, root *NewsPostQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NewsPostSelect is the builder for selecting fields of NewsPost entities.
type NewsPostSelect struct {
	*NewsPostQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *NewsPostSelect) Aggregate(fns ...AggregateFunc) *NewsPostSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *NewsPostSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NewsPostQuery, *NewsPostSelect](ctx, _s.NewsPostQuery, _s, _s.inters, v)
}

func (_s *NewsPostSelect) sqlScan(ctx context.Context, root *NewsPostQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
