// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dlxyz/SubioHub/ent/newspost"
	"github.com/dlxyz/SubioHub/ent/newsposttranslation"
	"github.com/dlxyz/SubioHub/ent/predicate"
)

// NewsPostUpdate is the builder for updating NewsPost entities.
type NewsPostUpdate struct {
	config
	hooks    []Hook
	mutation *NewsPostMutation
}

// Where appends a list predicates to the NewsPostUpdate builder.
func (_u *NewsPostUpdate) Where(ps ...predicate.NewsPost) *NewsPostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *NewsPostUpdate) SetSlug(v string) *NewsPostUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *NewsPostUpdate) SetNillableSlug(v *string) *NewsPostUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NewsPostUpdate) SetStatus(v string) *NewsPostUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NewsPostUpdate) SetNillableStatus(v *string) *NewsPostUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDefaultLocale sets the "default_locale" field.
func (_u *NewsPostUpdate) SetDefaultLocale(v string) *NewsPostUpdate {
	_u.mutation.SetDefaultLocale(v)
	return _u
}

// SetNillableDefaultLocale sets the "default_locale" field if the given value is not nil.
func (_u *NewsPostUpdate) SetNillableDefaultLocale(v *string) *NewsPostUpdate {
	if v != nil {
		_u.SetDefaultLocale(*v)
	}
	return _u
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_u *NewsPostUpdate) SetCoverImageURL(v string) *NewsPostUpdate {
	_u.mutation.SetCoverImageURL(v)
	return _u
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_u *NewsPostUpdate) SetNillableCoverImageURL(v *string) *NewsPostUpdate {
	if v != nil {
		_u.SetCoverImageURL(*v)
	}
	return _u
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (_u *NewsPostUpdate) ClearCoverImageURL() *NewsPostUpdate {
	_u.mutation.ClearCoverImageURL()
	return _u
}

// SetAuthorName sets the "author_name" field.
func (_u *NewsPostUpdate) SetAuthorName(v string) *NewsPostUpdate {
	_u.mutation.SetAuthorName(v)
	return _u
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_u *NewsPostUpdate) SetNillableAuthorName(v *string) *NewsPostUpdate {
	if v != nil {
		_u.SetAuthorName(*v)
	}
	return _u
}

// ClearAuthorName clears the value of the "author_name" field.
func (_u *NewsPostUpdate) ClearAuthorName() *NewsPostUpdate {
	_u.mutation.ClearAuthorName()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *NewsPostUpdate) SetPublishedAt(v time.Time) *NewsPostUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *NewsPostUpdate) SetNillablePublishedAt(v *time.Time) *NewsPostUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *NewsPostUpdate) ClearPublishedAt() *NewsPostUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *NewsPostUpdate) SetCreatedBy(v int64) *NewsPostUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *NewsPostUpdate) SetNillableCreatedBy(v *int64) *NewsPostUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *NewsPostUpdate) AddCreatedBy(v int64) *NewsPostUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *NewsPostUpdate) ClearCreatedBy() *NewsPostUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *NewsPostUpdate) SetUpdatedBy(v int64) *NewsPostUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *NewsPostUpdate) SetNillableUpdatedBy(v *int64) *NewsPostUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *NewsPostUpdate) AddUpdatedBy(v int64) *NewsPostUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *NewsPostUpdate) ClearUpdatedBy() *NewsPostUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NewsPostUpdate) SetUpdatedAt(v time.Time) *NewsPostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTranslationIDs adds the "translations" edge to the NewsPostTranslation entity by IDs.
func (_u *NewsPostUpdate) AddTranslationIDs(ids ...int64) *NewsPostUpdate {
	_u.mutation.AddTranslationIDs(ids...)
	return _u
}

// AddTranslations adds the "translations" edges to the NewsPostTranslation entity.
func (_u *NewsPostUpdate) AddTranslations(v ...*NewsPostTranslation) *NewsPostUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTranslationIDs(ids...)
}

// Mutation returns the NewsPostMutation object of the builder.
func (_u *NewsPostUpdate) Mutation() *NewsPostMutation {
	return _u.mutation
}

// ClearTranslations clears all "translations" edges to the NewsPostTranslation entity.
func (_u *NewsPostUpdate) ClearTranslations() *NewsPostUpdate {
	_u.mutation.ClearTranslations()
	return _u
}

// RemoveTranslationIDs removes the "translations" edge to NewsPostTranslation entities by IDs.
func (_u *NewsPostUpdate) RemoveTranslationIDs(ids ...int64) *NewsPostUpdate {
	_u.mutation.RemoveTranslationIDs(ids...)
	return _u
}

// RemoveTranslations removes "translations" edges to NewsPostTranslation entities.
func (_u *NewsPostUpdate) RemoveTranslations(v ...*NewsPostTranslation) *NewsPostUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTranslationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NewsPostUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NewsPostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NewsPostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NewsPostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NewsPostUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := newspost.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NewsPostUpdate) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := newspost.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "NewsPost.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := newspost.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "NewsPost.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultLocale(); ok {
		if err := newspost.DefaultLocaleValidator(v); err != nil {
			return &ValidationError{Name: "default_locale", err: fmt.Errorf(`ent: validator failed for field "NewsPost.default_locale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImageURL(); ok {
		if err := newspost.CoverImageURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_image_url", err: fmt.Errorf(`ent: validator failed for field "NewsPost.cover_image_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorName(); ok {
		if err := newspost.AuthorNameValidator(v); err != nil {
			return &ValidationError{Name: "author_name", err: fmt.Errorf(`ent: validator failed for field "NewsPost.author_name": %w`, err)}
		}
	}
	return nil
}

func (_u *NewsPostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(newspost.Table, newspost.Columns, sqlgraph.NewFieldSpec(newspost.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(newspost.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(newspost.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultLocale(); ok {
		_spec.SetField(newspost.FieldDefaultLocale, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoverImageURL(); ok {
		_spec.SetField(newspost.FieldCoverImageURL, field.TypeString, value)
	}
	if _u.mutation.CoverImageURLCleared() {
		_spec.ClearField(newspost.FieldCoverImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.AuthorName(); ok {
		_spec.SetField(newspost.FieldAuthorName, field.TypeString, value)
	}
	if _u.mutation.AuthorNameCleared() {
		_spec.ClearField(newspost.FieldAuthorName, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(newspost.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(newspost.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(newspost.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(newspost.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(newspost.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(newspost.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(newspost.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(newspost.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(newspost.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TranslationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   newspost.TranslationsTable,
			Columns: []string{newspost.TranslationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(newsposttranslation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTranslationsIDs(); len(nodes) > 0 && !_u.mutation.TranslationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   newspost.TranslationsTable,
			Columns: []string{newspost.TranslationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(newsposttranslation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TranslationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   newspost.TranslationsTable,
			Columns: []string{newspost.TranslationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(newsposttranslation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{newspost.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NewsPostUpdateOne is the builder for updating a single NewsPost entity.
type NewsPostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NewsPostMutation
}

// SetSlug sets the "slug" field.
func (_u *NewsPostUpdateOne) SetSlug(v string) *NewsPostUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *NewsPostUpdateOne) SetNillableSlug(v *string) *NewsPostUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NewsPostUpdateOne) SetStatus(v string) *NewsPostUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NewsPostUpdateOne) SetNillableStatus(v *string) *NewsPostUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDefaultLocale sets the "default_locale" field.
func (_u *NewsPostUpdateOne) SetDefaultLocale(v string) *NewsPostUpdateOne {
	_u.mutation.SetDefaultLocale(v)
	return _u
}

// SetNillableDefaultLocale sets the "default_locale" field if the given value is not nil.
func (_u *NewsPostUpdateOne) SetNillableDefaultLocale(v *string) *NewsPostUpdateOne {
	if v != nil {
		_u.SetDefaultLocale(*v)
	}
	return _u
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_u *NewsPostUpdateOne) SetCoverImageURL(v string) *NewsPostUpdateOne {
	_u.mutation.SetCoverImageURL(v)
	return _u
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_u *NewsPostUpdateOne) SetNillableCoverImageURL(v *string) *NewsPostUpdateOne {
	if v != nil {
		_u.SetCoverImageURL(*v)
	}
	return _u
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (_u *NewsPostUpdateOne) ClearCoverImageURL() *NewsPostUpdateOne {
	_u.mutation.ClearCoverImageURL()
	return _u
}

// SetAuthorName sets the "author_name" field.
func (_u *NewsPostUpdateOne) SetAuthorName(v string) *NewsPostUpdateOne {
	_u.mutation.SetAuthorName(v)
	return _u
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_u *NewsPostUpdateOne) SetNillableAuthorName(v *string) *NewsPostUpdateOne {
	if v != nil {
		_u.SetAuthorName(*v)
	}
	return _u
}

// ClearAuthorName clears the value of the "author_name" field.
func (_u *NewsPostUpdateOne) ClearAuthorName() *NewsPostUpdateOne {
	_u.mutation.ClearAuthorName()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *NewsPostUpdateOne) SetPublishedAt(v time.Time) *NewsPostUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *NewsPostUpdateOne) SetNillablePublishedAt(v *time.Time) *NewsPostUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *NewsPostUpdateOne) ClearPublishedAt() *NewsPostUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *NewsPostUpdateOne) SetCreatedBy(v int64) *NewsPostUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *NewsPostUpdateOne) SetNillableCreatedBy(v *int64) *NewsPostUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *NewsPostUpdateOne) AddCreatedBy(v int64) *NewsPostUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *NewsPostUpdateOne) ClearCreatedBy() *NewsPostUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *NewsPostUpdateOne) SetUpdatedBy(v int64) *NewsPostUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *NewsPostUpdateOne) SetNillableUpdatedBy(v *int64) *NewsPostUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *NewsPostUpdateOne) AddUpdatedBy(v int64) *NewsPostUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *NewsPostUpdateOne) ClearUpdatedBy() *NewsPostUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NewsPostUpdateOne) SetUpdatedAt(v time.Time) *NewsPostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTranslationIDs adds the "translations" edge to the NewsPostTranslation entity by IDs.
func (_u *NewsPostUpdateOne) AddTranslationIDs(ids ...int64) *NewsPostUpdateOne {
	_u.mutation.AddTranslationIDs(ids...)
	return _u
}

// AddTranslations adds the "translations" edges to the NewsPostTranslation entity.
func (_u *NewsPostUpdateOne) AddTranslations(v ...*NewsPostTranslation) *NewsPostUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTranslationIDs(ids...)
}

// Mutation returns the NewsPostMutation object of the builder.
func (_u *NewsPostUpdateOne) Mutation() *NewsPostMutation {
	return _u.mutation
}

// ClearTranslations clears all "translations" edges to the NewsPostTranslation entity.
func (_u *NewsPostUpdateOne) ClearTranslations() *NewsPostUpdateOne {
	_u.mutation.ClearTranslations()
	return _u
}

// RemoveTranslationIDs removes the "translations" edge to NewsPostTranslation entities by IDs.
func (_u *NewsPostUpdateOne) RemoveTranslationIDs(ids ...int64) *NewsPostUpdateOne {
	_u.mutation.RemoveTranslationIDs(ids...)
	return _u
}

// RemoveTranslations removes "translations" edges to NewsPostTranslation entities.
func (_u *NewsPostUpdateOne) RemoveTranslations(v ...*NewsPostTranslation) *NewsPostUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTranslationIDs(ids...)
}

// Where appends a list predicates to the NewsPostUpdate builder.
func (_u *NewsPostUpdateOne) Where(ps ...predicate.NewsPost) *NewsPostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NewsPostUpdateOne) Select(field string, fields ...string) *NewsPostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NewsPost entity.
func (_u *NewsPostUpdateOne) Save(ctx context.Context) (*NewsPost, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NewsPostUpdateOne) SaveX(ctx context.Context) *NewsPost {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NewsPostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NewsPostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NewsPostUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := newspost.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NewsPostUpdateOne) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := newspost.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "NewsPost.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := newspost.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "NewsPost.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultLocale(); ok {
		if err := newspost.DefaultLocaleValidator(v); err != nil {
			return &ValidationError{Name: "default_locale", err: fmt.Errorf(`ent: validator failed for field "NewsPost.default_locale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImageURL(); ok {
		if err := newspost.CoverImageURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_image_url", err: fmt.Errorf(`ent: validator failed for field "NewsPost.cover_image_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorName(); ok {
		if err := newspost.AuthorNameValidator(v); err != nil {
			return &ValidationError{Name: "author_name", err: fmt.Errorf(`ent: validator failed for field "NewsPost.author_name": %w`, err)}
		}
	}
	return nil
}

func (_u *NewsPostUpdateOne) sqlSave(ctx context.Context) (_node *NewsPost, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(newspost.Table, newspost.Columns, sqlgraph.NewFieldSpec(newspost.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NewsPost.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, newspost.FieldID)
		for _, f := range fields {
			if !newspost.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != newspost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(newspost.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(newspost.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultLocale(); ok {
		_spec.SetField(newspost.FieldDefaultLocale, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoverImageURL(); ok {
		_spec.SetField(newspost.FieldCoverImageURL, field.TypeString, value)
	}
	if _u.mutation.CoverImageURLCleared() {
		_spec.ClearField(newspost.FieldCoverImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.AuthorName(); ok {
		_spec.SetField(newspost.FieldAuthorName, field.TypeString, value)
	}
	if _u.mutation.AuthorNameCleared() {
		_spec.ClearField(newspost.FieldAuthorName, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(newspost.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(newspost.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(newspost.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(newspost.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(newspost.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(newspost.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(newspost.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(newspost.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(newspost.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TranslationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   newspost.TranslationsTable,
			Columns: []string{newspost.TranslationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(newsposttranslation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTranslationsIDs(); len(nodes) > 0 && !_u.mutation.TranslationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   newspost.TranslationsTable,
			Columns: []string{newspost.TranslationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(newsposttranslation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TranslationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   newspost.TranslationsTable,
			Columns: []string{newspost.TranslationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(newsposttranslation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NewsPost{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{newspost.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
