// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dlxyz/SubioHub/ent/newspost"
	"github.com/dlxyz/SubioHub/ent/newsposttranslation"
)

// NewsPostTranslation is the model entity for the NewsPostTranslation schema.
type NewsPostTranslation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// NewsPostID holds the value of the "news_post_id" field.
	NewsPostID int64 `json:"news_post_id,omitempty"`
	// 语言代码，如 zh-CN、en-US
	Locale string `json:"locale,omitempty"`
	// 资讯标题
	Title string `json:"title,omitempty"`
	// 摘要
	Summary string `json:"summary,omitempty"`
	// HTML 正文
	Content string `json:"content,omitempty"`
	// SEO 标题
	SeoTitle *string `json:"seo_title,omitempty"`
	// SEO 描述
	SeoDescription *string `json:"seo_description,omitempty"`
	// 翻译状态: manual, ai_draft, reviewed
	TranslationStatus string `json:"translation_status,omitempty"`
	// 翻译来源
	TranslationProvider *string `json:"translation_provider,omitempty"`
	// 翻译来源语言
	TranslatedFromLocale *string `json:"translated_from_locale,omitempty"`
	// 最后翻译时间
	LastTranslatedAt *time.Time `json:"last_translated_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NewsPostTranslationQuery when eager-loading is set.
	Edges        NewsPostTranslationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NewsPostTranslationEdges holds the relations/edges for other nodes in the graph.
type NewsPostTranslationEdges struct {
	// NewsPost holds the value of the news_post edge.
	NewsPost *NewsPost `json:"news_post,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NewsPostOrErr returns the NewsPost value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NewsPostTranslationEdges) NewsPostOrErr() (*NewsPost, error) {
	if e.NewsPost != nil {
		return e.NewsPost, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: newspost.Label}
	}
	return nil, &NotLoadedError{edge: "news_post"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NewsPostTranslation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case newsposttranslation.FieldID, newsposttranslation.FieldNewsPostID:
			values[i] = new(sql.NullInt64)
		case newsposttranslation.FieldLocale, newsposttranslation.FieldTitle, newsposttranslation.FieldSummary, newsposttranslation.FieldContent, newsposttranslation.FieldSeoTitle, newsposttranslation.FieldSeoDescription, newsposttranslation.FieldTranslationStatus, newsposttranslation.FieldTranslationProvider, newsposttranslation.FieldTranslatedFromLocale:
			values[i] = new(sql.NullString)
		case newsposttranslation.FieldLastTranslatedAt, newsposttranslation.FieldCreatedAt, newsposttranslation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NewsPostTranslation fields.
func (_m *NewsPostTranslation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case newsposttranslation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case newsposttranslation.FieldNewsPostID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field news_post_id", values[i])
			} else if value.Valid {
				_m.NewsPostID = value.Int64
			}
		case newsposttranslation.FieldLocale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locale", values[i])
			} else if value.Valid {
				_m.Locale = value.String
			}
		case newsposttranslation.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case newsposttranslation.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case newsposttranslation.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case newsposttranslation.FieldSeoTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field seo_title", values[i])
			} else if value.Valid {
				_m.SeoTitle = new(string)
				*_m.SeoTitle = value.String
			}
		case newsposttranslation.FieldSeoDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field seo_description", values[i])
			} else if value.Valid {
				_m.SeoDescription = new(string)
				*_m.SeoDescription = value.String
			}
		case newsposttranslation.FieldTranslationStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field translation_status", values[i])
			} else if value.Valid {
				_m.TranslationStatus = value.String
			}
		case newsposttranslation.FieldTranslationProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field translation_provider", values[i])
			} else if value.Valid {
				_m.TranslationProvider = new(string)
				*_m.TranslationProvider = value.String
			}
		case newsposttranslation.FieldTranslatedFromLocale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field translated_from_locale", values[i])
			} else if value.Valid {
				_m.TranslatedFromLocale = new(string)
				*_m.TranslatedFromLocale = value.String
			}
		case newsposttranslation.FieldLastTranslatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_translated_at", values[i])
			} else if value.Valid {
				_m.LastTranslatedAt = new(time.Time)
				*_m.LastTranslatedAt = value.Time
			}
		case newsposttranslation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case newsposttranslation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NewsPostTranslation.
// This includes values selected through modifiers, order, etc.
func (_m *NewsPostTranslation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryNewsPost queries the "news_post" edge of the NewsPostTranslation entity.
func (_m *NewsPostTranslation) QueryNewsPost() *NewsPostQuery {
	return NewNewsPostTranslationClient(_m.config).QueryNewsPost(_m)
}

// Update returns a builder for updating this NewsPostTranslation.
// Note that you need to call NewsPostTranslation.Unwrap() before calling this method if this NewsPostTranslation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NewsPostTranslation) Update() *NewsPostTranslationUpdateOne {
	return NewNewsPostTranslationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NewsPostTranslation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NewsPostTranslation) Unwrap() *NewsPostTranslation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NewsPostTranslation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NewsPostTranslation) String() string {
	var builder strings.Builder
	builder.WriteString("NewsPostTranslation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("news_post_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.NewsPostID))
	builder.WriteString(", ")
	builder.WriteString("locale=")
	builder.WriteString(_m.Locale)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	if v := _m.SeoTitle; v != nil {
		builder.WriteString("seo_title=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SeoDescription; v != nil {
		builder.WriteString("seo_description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("translation_status=")
	builder.WriteString(_m.TranslationStatus)
	builder.WriteString(", ")
	if v := _m.TranslationProvider; v != nil {
		builder.WriteString("translation_provider=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TranslatedFromLocale; v != nil {
		builder.WriteString("translated_from_locale=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastTranslatedAt; v != nil {
		builder.WriteString("last_translated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NewsPostTranslations is a parsable slice of NewsPostTranslation.
type NewsPostTranslations []*NewsPostTranslation
