// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dlxyz/SubioHub/ent/predicate"
	"github.com/dlxyz/SubioHub/ent/promotionrelation"
)

// PromotionRelationDelete is the builder for deleting a PromotionRelation entity.
type PromotionRelationDelete struct {
	config
	hooks    []Hook
	mutation *PromotionRelationMutation
}

// Where appends a list predicates to the PromotionRelationDelete builder.
func (_d *PromotionRelationDelete) Where(ps ...predicate.PromotionRelation) *PromotionRelationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PromotionRelationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PromotionRelationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PromotionRelationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(promotionrelation.Table, sqlgraph.NewFieldSpec(promotionrelation.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PromotionRelationDeleteOne is the builder for deleting a single PromotionRelation entity.
type PromotionRelationDeleteOne struct {
	_d *PromotionRelationDelete
}

// Where appends a list predicates to the PromotionRelationDelete builder.
func (_d *PromotionRelationDeleteOne) Where(ps ...predicate.PromotionRelation) *PromotionRelationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PromotionRelationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{promotionrelation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PromotionRelationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
