// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dlxyz/SubioHub/ent/predicate"
	"github.com/dlxyz/SubioHub/ent/promotionrelation"
	"github.com/dlxyz/SubioHub/ent/user"
)

// PromotionRelationUpdate is the builder for updating PromotionRelation entities.
type PromotionRelationUpdate struct {
	config
	hooks    []Hook
	mutation *PromotionRelationMutation
}

// Where appends a list predicates to the PromotionRelationUpdate builder.
func (_u *PromotionRelationUpdate) Where(ps ...predicate.PromotionRelation) *PromotionRelationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromotionRelationUpdate) SetUpdatedAt(v time.Time) *PromotionRelationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PromotionRelationUpdate) SetUserID(v int64) *PromotionRelationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PromotionRelationUpdate) SetNillableUserID(v *int64) *PromotionRelationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetChannelPartnerUserID sets the "channel_partner_user_id" field.
func (_u *PromotionRelationUpdate) SetChannelPartnerUserID(v int64) *PromotionRelationUpdate {
	_u.mutation.SetChannelPartnerUserID(v)
	return _u
}

// SetNillableChannelPartnerUserID sets the "channel_partner_user_id" field if the given value is not nil.
func (_u *PromotionRelationUpdate) SetNillableChannelPartnerUserID(v *int64) *PromotionRelationUpdate {
	if v != nil {
		_u.SetChannelPartnerUserID(*v)
	}
	return _u
}

// ClearChannelPartnerUserID clears the value of the "channel_partner_user_id" field.
func (_u *PromotionRelationUpdate) ClearChannelPartnerUserID() *PromotionRelationUpdate {
	_u.mutation.ClearChannelPartnerUserID()
	return _u
}

// SetAgentUserID sets the "agent_user_id" field.
func (_u *PromotionRelationUpdate) SetAgentUserID(v int64) *PromotionRelationUpdate {
	_u.mutation.SetAgentUserID(v)
	return _u
}

// SetNillableAgentUserID sets the "agent_user_id" field if the given value is not nil.
func (_u *PromotionRelationUpdate) SetNillableAgentUserID(v *int64) *PromotionRelationUpdate {
	if v != nil {
		_u.SetAgentUserID(*v)
	}
	return _u
}

// ClearAgentUserID clears the value of the "agent_user_id" field.
func (_u *PromotionRelationUpdate) ClearAgentUserID() *PromotionRelationUpdate {
	_u.mutation.ClearAgentUserID()
	return _u
}

// SetDistributorUserID sets the "distributor_user_id" field.
func (_u *PromotionRelationUpdate) SetDistributorUserID(v int64) *PromotionRelationUpdate {
	_u.mutation.SetDistributorUserID(v)
	return _u
}

// SetNillableDistributorUserID sets the "distributor_user_id" field if the given value is not nil.
func (_u *PromotionRelationUpdate) SetNillableDistributorUserID(v *int64) *PromotionRelationUpdate {
	if v != nil {
		_u.SetDistributorUserID(*v)
	}
	return _u
}

// ClearDistributorUserID clears the value of the "distributor_user_id" field.
func (_u *PromotionRelationUpdate) ClearDistributorUserID() *PromotionRelationUpdate {
	_u.mutation.ClearDistributorUserID()
	return _u
}

// SetDirectParentUserID sets the "direct_parent_user_id" field.
func (_u *PromotionRelationUpdate) SetDirectParentUserID(v int64) *PromotionRelationUpdate {
	_u.mutation.SetDirectParentUserID(v)
	return _u
}

// SetNillableDirectParentUserID sets the "direct_parent_user_id" field if the given value is not nil.
func (_u *PromotionRelationUpdate) SetNillableDirectParentUserID(v *int64) *PromotionRelationUpdate {
	if v != nil {
		_u.SetDirectParentUserID(*v)
	}
	return _u
}

// ClearDirectParentUserID clears the value of the "direct_parent_user_id" field.
func (_u *PromotionRelationUpdate) ClearDirectParentUserID() *PromotionRelationUpdate {
	_u.mutation.ClearDirectParentUserID()
	return _u
}

// SetDirectParentRole sets the "direct_parent_role" field.
func (_u *PromotionRelationUpdate) SetDirectParentRole(v string) *PromotionRelationUpdate {
	_u.mutation.SetDirectParentRole(v)
	return _u
}

// SetNillableDirectParentRole sets the "direct_parent_role" field if the given value is not nil.
func (_u *PromotionRelationUpdate) SetNillableDirectParentRole(v *string) *PromotionRelationUpdate {
	if v != nil {
		_u.SetDirectParentRole(*v)
	}
	return _u
}

// SetBindingSource sets the "binding_source" field.
func (_u *PromotionRelationUpdate) SetBindingSource(v string) *PromotionRelationUpdate {
	_u.mutation.SetBindingSource(v)
	return _u
}

// SetNillableBindingSource sets the "binding_source" field if the given value is not nil.
func (_u *PromotionRelationUpdate) SetNillableBindingSource(v *string) *PromotionRelationUpdate {
	if v != nil {
		_u.SetBindingSource(*v)
	}
	return _u
}

// SetIsLocked sets the "is_locked" field.
func (_u *PromotionRelationUpdate) SetIsLocked(v bool) *PromotionRelationUpdate {
	_u.mutation.SetIsLocked(v)
	return _u
}

// SetNillableIsLocked sets the "is_locked" field if the given value is not nil.
func (_u *PromotionRelationUpdate) SetNillableIsLocked(v *bool) *PromotionRelationUpdate {
	if v != nil {
		_u.SetIsLocked(*v)
	}
	return _u
}

// SetBoundAt sets the "bound_at" field.
func (_u *PromotionRelationUpdate) SetBoundAt(v time.Time) *PromotionRelationUpdate {
	_u.mutation.SetBoundAt(v)
	return _u
}

// SetNillableBoundAt sets the "bound_at" field if the given value is not nil.
func (_u *PromotionRelationUpdate) SetNillableBoundAt(v *time.Time) *PromotionRelationUpdate {
	if v != nil {
		_u.SetBoundAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PromotionRelationUpdate) SetNotes(v string) *PromotionRelationUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PromotionRelationUpdate) SetNillableNotes(v *string) *PromotionRelationUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *PromotionRelationUpdate) ClearNotes() *PromotionRelationUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PromotionRelationUpdate) SetUser(v *User) *PromotionRelationUpdate {
	return _u.SetUserID(v.ID)
}

// SetChannelPartnerUser sets the "channel_partner_user" edge to the User entity.
func (_u *PromotionRelationUpdate) SetChannelPartnerUser(v *User) *PromotionRelationUpdate {
	return _u.SetChannelPartnerUserID(v.ID)
}

// SetAgentUser sets the "agent_user" edge to the User entity.
func (_u *PromotionRelationUpdate) SetAgentUser(v *User) *PromotionRelationUpdate {
	return _u.SetAgentUserID(v.ID)
}

// SetDistributorUser sets the "distributor_user" edge to the User entity.
func (_u *PromotionRelationUpdate) SetDistributorUser(v *User) *PromotionRelationUpdate {
	return _u.SetDistributorUserID(v.ID)
}

// SetDirectParentUser sets the "direct_parent_user" edge to the User entity.
func (_u *PromotionRelationUpdate) SetDirectParentUser(v *User) *PromotionRelationUpdate {
	return _u.SetDirectParentUserID(v.ID)
}

// Mutation returns the PromotionRelationMutation object of the builder.
func (_u *PromotionRelationUpdate) Mutation() *PromotionRelationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PromotionRelationUpdate) ClearUser() *PromotionRelationUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearChannelPartnerUser clears the "channel_partner_user" edge to the User entity.
func (_u *PromotionRelationUpdate) ClearChannelPartnerUser() *PromotionRelationUpdate {
	_u.mutation.ClearChannelPartnerUser()
	return _u
}

// ClearAgentUser clears the "agent_user" edge to the User entity.
func (_u *PromotionRelationUpdate) ClearAgentUser() *PromotionRelationUpdate {
	_u.mutation.ClearAgentUser()
	return _u
}

// ClearDistributorUser clears the "distributor_user" edge to the User entity.
func (_u *PromotionRelationUpdate) ClearDistributorUser() *PromotionRelationUpdate {
	_u.mutation.ClearDistributorUser()
	return _u
}

// ClearDirectParentUser clears the "direct_parent_user" edge to the User entity.
func (_u *PromotionRelationUpdate) ClearDirectParentUser() *PromotionRelationUpdate {
	_u.mutation.ClearDirectParentUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromotionRelationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromotionRelationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromotionRelationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromotionRelationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromotionRelationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promotionrelation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromotionRelationUpdate) check() error {
	if v, ok := _u.mutation.DirectParentRole(); ok {
		if err := promotionrelation.DirectParentRoleValidator(v); err != nil {
			return &ValidationError{Name: "direct_parent_role", err: fmt.Errorf(`ent: validator failed for field "PromotionRelation.direct_parent_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BindingSource(); ok {
		if err := promotionrelation.BindingSourceValidator(v); err != nil {
			return &ValidationError{Name: "binding_source", err: fmt.Errorf(`ent: validator failed for field "PromotionRelation.binding_source": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PromotionRelation.user"`)
	}
	return nil
}

func (_u *PromotionRelationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promotionrelation.Table, promotionrelation.Columns, sqlgraph.NewFieldSpec(promotionrelation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promotionrelation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DirectParentRole(); ok {
		_spec.SetField(promotionrelation.FieldDirectParentRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.BindingSource(); ok {
		_spec.SetField(promotionrelation.FieldBindingSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsLocked(); ok {
		_spec.SetField(promotionrelation.FieldIsLocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BoundAt(); ok {
		_spec.SetField(promotionrelation.FieldBoundAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(promotionrelation.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(promotionrelation.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.UserTable,
			Columns: []string{promotionrelation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.UserTable,
			Columns: []string{promotionrelation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelPartnerUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.ChannelPartnerUserTable,
			Columns: []string{promotionrelation.ChannelPartnerUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelPartnerUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.ChannelPartnerUserTable,
			Columns: []string{promotionrelation.ChannelPartnerUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.AgentUserTable,
			Columns: []string{promotionrelation.AgentUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.AgentUserTable,
			Columns: []string{promotionrelation.AgentUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DistributorUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.DistributorUserTable,
			Columns: []string{promotionrelation.DistributorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DistributorUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.DistributorUserTable,
			Columns: []string{promotionrelation.DistributorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DirectParentUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.DirectParentUserTable,
			Columns: []string{promotionrelation.DirectParentUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DirectParentUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.DirectParentUserTable,
			Columns: []string{promotionrelation.DirectParentUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promotionrelation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromotionRelationUpdateOne is the builder for updating a single PromotionRelation entity.
type PromotionRelationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PromotionRelationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromotionRelationUpdateOne) SetUpdatedAt(v time.Time) *PromotionRelationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PromotionRelationUpdateOne) SetUserID(v int64) *PromotionRelationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PromotionRelationUpdateOne) SetNillableUserID(v *int64) *PromotionRelationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetChannelPartnerUserID sets the "channel_partner_user_id" field.
func (_u *PromotionRelationUpdateOne) SetChannelPartnerUserID(v int64) *PromotionRelationUpdateOne {
	_u.mutation.SetChannelPartnerUserID(v)
	return _u
}

// SetNillableChannelPartnerUserID sets the "channel_partner_user_id" field if the given value is not nil.
func (_u *PromotionRelationUpdateOne) SetNillableChannelPartnerUserID(v *int64) *PromotionRelationUpdateOne {
	if v != nil {
		_u.SetChannelPartnerUserID(*v)
	}
	return _u
}

// ClearChannelPartnerUserID clears the value of the "channel_partner_user_id" field.
func (_u *PromotionRelationUpdateOne) ClearChannelPartnerUserID() *PromotionRelationUpdateOne {
	_u.mutation.ClearChannelPartnerUserID()
	return _u
}

// SetAgentUserID sets the "agent_user_id" field.
func (_u *PromotionRelationUpdateOne) SetAgentUserID(v int64) *PromotionRelationUpdateOne {
	_u.mutation.SetAgentUserID(v)
	return _u
}

// SetNillableAgentUserID sets the "agent_user_id" field if the given value is not nil.
func (_u *PromotionRelationUpdateOne) SetNillableAgentUserID(v *int64) *PromotionRelationUpdateOne {
	if v != nil {
		_u.SetAgentUserID(*v)
	}
	return _u
}

// ClearAgentUserID clears the value of the "agent_user_id" field.
func (_u *PromotionRelationUpdateOne) ClearAgentUserID() *PromotionRelationUpdateOne {
	_u.mutation.ClearAgentUserID()
	return _u
}

// SetDistributorUserID sets the "distributor_user_id" field.
func (_u *PromotionRelationUpdateOne) SetDistributorUserID(v int64) *PromotionRelationUpdateOne {
	_u.mutation.SetDistributorUserID(v)
	return _u
}

// SetNillableDistributorUserID sets the "distributor_user_id" field if the given value is not nil.
func (_u *PromotionRelationUpdateOne) SetNillableDistributorUserID(v *int64) *PromotionRelationUpdateOne {
	if v != nil {
		_u.SetDistributorUserID(*v)
	}
	return _u
}

// ClearDistributorUserID clears the value of the "distributor_user_id" field.
func (_u *PromotionRelationUpdateOne) ClearDistributorUserID() *PromotionRelationUpdateOne {
	_u.mutation.ClearDistributorUserID()
	return _u
}

// SetDirectParentUserID sets the "direct_parent_user_id" field.
func (_u *PromotionRelationUpdateOne) SetDirectParentUserID(v int64) *PromotionRelationUpdateOne {
	_u.mutation.SetDirectParentUserID(v)
	return _u
}

// SetNillableDirectParentUserID sets the "direct_parent_user_id" field if the given value is not nil.
func (_u *PromotionRelationUpdateOne) SetNillableDirectParentUserID(v *int64) *PromotionRelationUpdateOne {
	if v != nil {
		_u.SetDirectParentUserID(*v)
	}
	return _u
}

// ClearDirectParentUserID clears the value of the "direct_parent_user_id" field.
func (_u *PromotionRelationUpdateOne) ClearDirectParentUserID() *PromotionRelationUpdateOne {
	_u.mutation.ClearDirectParentUserID()
	return _u
}

// SetDirectParentRole sets the "direct_parent_role" field.
func (_u *PromotionRelationUpdateOne) SetDirectParentRole(v string) *PromotionRelationUpdateOne {
	_u.mutation.SetDirectParentRole(v)
	return _u
}

// SetNillableDirectParentRole sets the "direct_parent_role" field if the given value is not nil.
func (_u *PromotionRelationUpdateOne) SetNillableDirectParentRole(v *string) *PromotionRelationUpdateOne {
	if v != nil {
		_u.SetDirectParentRole(*v)
	}
	return _u
}

// SetBindingSource sets the "binding_source" field.
func (_u *PromotionRelationUpdateOne) SetBindingSource(v string) *PromotionRelationUpdateOne {
	_u.mutation.SetBindingSource(v)
	return _u
}

// SetNillableBindingSource sets the "binding_source" field if the given value is not nil.
func (_u *PromotionRelationUpdateOne) SetNillableBindingSource(v *string) *PromotionRelationUpdateOne {
	if v != nil {
		_u.SetBindingSource(*v)
	}
	return _u
}

// SetIsLocked sets the "is_locked" field.
func (_u *PromotionRelationUpdateOne) SetIsLocked(v bool) *PromotionRelationUpdateOne {
	_u.mutation.SetIsLocked(v)
	return _u
}

// SetNillableIsLocked sets the "is_locked" field if the given value is not nil.
func (_u *PromotionRelationUpdateOne) SetNillableIsLocked(v *bool) *PromotionRelationUpdateOne {
	if v != nil {
		_u.SetIsLocked(*v)
	}
	return _u
}

// SetBoundAt sets the "bound_at" field.
func (_u *PromotionRelationUpdateOne) SetBoundAt(v time.Time) *PromotionRelationUpdateOne {
	_u.mutation.SetBoundAt(v)
	return _u
}

// SetNillableBoundAt sets the "bound_at" field if the given value is not nil.
func (_u *PromotionRelationUpdateOne) SetNillableBoundAt(v *time.Time) *PromotionRelationUpdateOne {
	if v != nil {
		_u.SetBoundAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PromotionRelationUpdateOne) SetNotes(v string) *PromotionRelationUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PromotionRelationUpdateOne) SetNillableNotes(v *string) *PromotionRelationUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *PromotionRelationUpdateOne) ClearNotes() *PromotionRelationUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PromotionRelationUpdateOne) SetUser(v *User) *PromotionRelationUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetChannelPartnerUser sets the "channel_partner_user" edge to the User entity.
func (_u *PromotionRelationUpdateOne) SetChannelPartnerUser(v *User) *PromotionRelationUpdateOne {
	return _u.SetChannelPartnerUserID(v.ID)
}

// SetAgentUser sets the "agent_user" edge to the User entity.
func (_u *PromotionRelationUpdateOne) SetAgentUser(v *User) *PromotionRelationUpdateOne {
	return _u.SetAgentUserID(v.ID)
}

// SetDistributorUser sets the "distributor_user" edge to the User entity.
func (_u *PromotionRelationUpdateOne) SetDistributorUser(v *User) *PromotionRelationUpdateOne {
	return _u.SetDistributorUserID(v.ID)
}

// SetDirectParentUser sets the "direct_parent_user" edge to the User entity.
func (_u *PromotionRelationUpdateOne) SetDirectParentUser(v *User) *PromotionRelationUpdateOne {
	return _u.SetDirectParentUserID(v.ID)
}

// Mutation returns the PromotionRelationMutation object of the builder.
func (_u *PromotionRelationUpdateOne) Mutation() *PromotionRelationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PromotionRelationUpdateOne) ClearUser() *PromotionRelationUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearChannelPartnerUser clears the "channel_partner_user" edge to the User entity.
func (_u *PromotionRelationUpdateOne) ClearChannelPartnerUser() *PromotionRelationUpdateOne {
	_u.mutation.ClearChannelPartnerUser()
	return _u
}

// ClearAgentUser clears the "agent_user" edge to the User entity.
func (_u *PromotionRelationUpdateOne) ClearAgentUser() *PromotionRelationUpdateOne {
	_u.mutation.ClearAgentUser()
	return _u
}

// ClearDistributorUser clears the "distributor_user" edge to the User entity.
func (_u *PromotionRelationUpdateOne) ClearDistributorUser() *PromotionRelationUpdateOne {
	_u.mutation.ClearDistributorUser()
	return _u
}

// ClearDirectParentUser clears the "direct_parent_user" edge to the User entity.
func (_u *PromotionRelationUpdateOne) ClearDirectParentUser() *PromotionRelationUpdateOne {
	_u.mutation.ClearDirectParentUser()
	return _u
}

// Where appends a list predicates to the PromotionRelationUpdate builder.
func (_u *PromotionRelationUpdateOne) Where(ps ...predicate.PromotionRelation) *PromotionRelationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromotionRelationUpdateOne) Select(field string, fields ...string) *PromotionRelationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PromotionRelation entity.
func (_u *PromotionRelationUpdateOne) Save(ctx context.Context) (*PromotionRelation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromotionRelationUpdateOne) SaveX(ctx context.Context) *PromotionRelation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromotionRelationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromotionRelationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromotionRelationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promotionrelation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromotionRelationUpdateOne) check() error {
	if v, ok := _u.mutation.DirectParentRole(); ok {
		if err := promotionrelation.DirectParentRoleValidator(v); err != nil {
			return &ValidationError{Name: "direct_parent_role", err: fmt.Errorf(`ent: validator failed for field "PromotionRelation.direct_parent_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BindingSource(); ok {
		if err := promotionrelation.BindingSourceValidator(v); err != nil {
			return &ValidationError{Name: "binding_source", err: fmt.Errorf(`ent: validator failed for field "PromotionRelation.binding_source": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PromotionRelation.user"`)
	}
	return nil
}

func (_u *PromotionRelationUpdateOne) sqlSave(ctx context.Context) (_node *PromotionRelation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promotionrelation.Table, promotionrelation.Columns, sqlgraph.NewFieldSpec(promotionrelation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PromotionRelation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promotionrelation.FieldID)
		for _, f := range fields {
			if !promotionrelation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != promotionrelation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promotionrelation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DirectParentRole(); ok {
		_spec.SetField(promotionrelation.FieldDirectParentRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.BindingSource(); ok {
		_spec.SetField(promotionrelation.FieldBindingSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsLocked(); ok {
		_spec.SetField(promotionrelation.FieldIsLocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BoundAt(); ok {
		_spec.SetField(promotionrelation.FieldBoundAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(promotionrelation.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(promotionrelation.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.UserTable,
			Columns: []string{promotionrelation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.UserTable,
			Columns: []string{promotionrelation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelPartnerUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.ChannelPartnerUserTable,
			Columns: []string{promotionrelation.ChannelPartnerUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelPartnerUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.ChannelPartnerUserTable,
			Columns: []string{promotionrelation.ChannelPartnerUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.AgentUserTable,
			Columns: []string{promotionrelation.AgentUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.AgentUserTable,
			Columns: []string{promotionrelation.AgentUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DistributorUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.DistributorUserTable,
			Columns: []string{promotionrelation.DistributorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DistributorUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.DistributorUserTable,
			Columns: []string{promotionrelation.DistributorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DirectParentUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.DirectParentUserTable,
			Columns: []string{promotionrelation.DirectParentUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DirectParentUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   promotionrelation.DirectParentUserTable,
			Columns: []string{promotionrelation.DirectParentUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PromotionRelation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promotionrelation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
