// Code generated by ent, DO NOT EDIT.

package newsposttranslation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/dlxyz/SubioHub/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLTE(FieldID, id))
}

// NewsPostID applies equality check predicate on the "news_post_id" field. It's identical to NewsPostIDEQ.
func NewsPostID(v int64) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldNewsPostID, v))
}

// Locale applies equality check predicate on the "locale" field. It's identical to LocaleEQ.
func Locale(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldLocale, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldTitle, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldSummary, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldContent, v))
}

// SeoTitle applies equality check predicate on the "seo_title" field. It's identical to SeoTitleEQ.
func SeoTitle(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldSeoTitle, v))
}

// SeoDescription applies equality check predicate on the "seo_description" field. It's identical to SeoDescriptionEQ.
func SeoDescription(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldSeoDescription, v))
}

// TranslationStatus applies equality check predicate on the "translation_status" field. It's identical to TranslationStatusEQ.
func TranslationStatus(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldTranslationStatus, v))
}

// TranslationProvider applies equality check predicate on the "translation_provider" field. It's identical to TranslationProviderEQ.
func TranslationProvider(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldTranslationProvider, v))
}

// TranslatedFromLocale applies equality check predicate on the "translated_from_locale" field. It's identical to TranslatedFromLocaleEQ.
func TranslatedFromLocale(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldTranslatedFromLocale, v))
}

// LastTranslatedAt applies equality check predicate on the "last_translated_at" field. It's identical to LastTranslatedAtEQ.
func LastTranslatedAt(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldLastTranslatedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldUpdatedAt, v))
}

// NewsPostIDEQ applies the EQ predicate on the "news_post_id" field.
func NewsPostIDEQ(v int64) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldNewsPostID, v))
}

// NewsPostIDNEQ applies the NEQ predicate on the "news_post_id" field.
func NewsPostIDNEQ(v int64) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNEQ(FieldNewsPostID, v))
}

// NewsPostIDIn applies the In predicate on the "news_post_id" field.
func NewsPostIDIn(vs ...int64) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIn(FieldNewsPostID, vs...))
}

// NewsPostIDNotIn applies the NotIn predicate on the "news_post_id" field.
func NewsPostIDNotIn(vs ...int64) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotIn(FieldNewsPostID, vs...))
}

// LocaleEQ applies the EQ predicate on the "locale" field.
func LocaleEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldLocale, v))
}

// LocaleNEQ applies the NEQ predicate on the "locale" field.
func LocaleNEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNEQ(FieldLocale, v))
}

// LocaleIn applies the In predicate on the "locale" field.
func LocaleIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIn(FieldLocale, vs...))
}

// LocaleNotIn applies the NotIn predicate on the "locale" field.
func LocaleNotIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotIn(FieldLocale, vs...))
}

// LocaleGT applies the GT predicate on the "locale" field.
func LocaleGT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGT(FieldLocale, v))
}

// LocaleGTE applies the GTE predicate on the "locale" field.
func LocaleGTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGTE(FieldLocale, v))
}

// LocaleLT applies the LT predicate on the "locale" field.
func LocaleLT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLT(FieldLocale, v))
}

// LocaleLTE applies the LTE predicate on the "locale" field.
func LocaleLTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLTE(FieldLocale, v))
}

// LocaleContains applies the Contains predicate on the "locale" field.
func LocaleContains(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContains(FieldLocale, v))
}

// LocaleHasPrefix applies the HasPrefix predicate on the "locale" field.
func LocaleHasPrefix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasPrefix(FieldLocale, v))
}

// LocaleHasSuffix applies the HasSuffix predicate on the "locale" field.
func LocaleHasSuffix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasSuffix(FieldLocale, v))
}

// LocaleEqualFold applies the EqualFold predicate on the "locale" field.
func LocaleEqualFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEqualFold(FieldLocale, v))
}

// LocaleContainsFold applies the ContainsFold predicate on the "locale" field.
func LocaleContainsFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContainsFold(FieldLocale, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContainsFold(FieldTitle, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryIsNil applies the IsNil predicate on the "summary" field.
func SummaryIsNil() predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIsNull(FieldSummary))
}

// SummaryNotNil applies the NotNil predicate on the "summary" field.
func SummaryNotNil() predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotNull(FieldSummary))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContainsFold(FieldSummary, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContainsFold(FieldContent, v))
}

// SeoTitleEQ applies the EQ predicate on the "seo_title" field.
func SeoTitleEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldSeoTitle, v))
}

// SeoTitleNEQ applies the NEQ predicate on the "seo_title" field.
func SeoTitleNEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNEQ(FieldSeoTitle, v))
}

// SeoTitleIn applies the In predicate on the "seo_title" field.
func SeoTitleIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIn(FieldSeoTitle, vs...))
}

// SeoTitleNotIn applies the NotIn predicate on the "seo_title" field.
func SeoTitleNotIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotIn(FieldSeoTitle, vs...))
}

// SeoTitleGT applies the GT predicate on the "seo_title" field.
func SeoTitleGT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGT(FieldSeoTitle, v))
}

// SeoTitleGTE applies the GTE predicate on the "seo_title" field.
func SeoTitleGTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGTE(FieldSeoTitle, v))
}

// SeoTitleLT applies the LT predicate on the "seo_title" field.
func SeoTitleLT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLT(FieldSeoTitle, v))
}

// SeoTitleLTE applies the LTE predicate on the "seo_title" field.
func SeoTitleLTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLTE(FieldSeoTitle, v))
}

// SeoTitleContains applies the Contains predicate on the "seo_title" field.
func SeoTitleContains(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContains(FieldSeoTitle, v))
}

// SeoTitleHasPrefix applies the HasPrefix predicate on the "seo_title" field.
func SeoTitleHasPrefix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasPrefix(FieldSeoTitle, v))
}

// SeoTitleHasSuffix applies the HasSuffix predicate on the "seo_title" field.
func SeoTitleHasSuffix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasSuffix(FieldSeoTitle, v))
}

// SeoTitleIsNil applies the IsNil predicate on the "seo_title" field.
func SeoTitleIsNil() predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIsNull(FieldSeoTitle))
}

// SeoTitleNotNil applies the NotNil predicate on the "seo_title" field.
func SeoTitleNotNil() predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotNull(FieldSeoTitle))
}

// SeoTitleEqualFold applies the EqualFold predicate on the "seo_title" field.
func SeoTitleEqualFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEqualFold(FieldSeoTitle, v))
}

// SeoTitleContainsFold applies the ContainsFold predicate on the "seo_title" field.
func SeoTitleContainsFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContainsFold(FieldSeoTitle, v))
}

// SeoDescriptionEQ applies the EQ predicate on the "seo_description" field.
func SeoDescriptionEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldSeoDescription, v))
}

// SeoDescriptionNEQ applies the NEQ predicate on the "seo_description" field.
func SeoDescriptionNEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNEQ(FieldSeoDescription, v))
}

// SeoDescriptionIn applies the In predicate on the "seo_description" field.
func SeoDescriptionIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIn(FieldSeoDescription, vs...))
}

// SeoDescriptionNotIn applies the NotIn predicate on the "seo_description" field.
func SeoDescriptionNotIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotIn(FieldSeoDescription, vs...))
}

// SeoDescriptionGT applies the GT predicate on the "seo_description" field.
func SeoDescriptionGT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGT(FieldSeoDescription, v))
}

// SeoDescriptionGTE applies the GTE predicate on the "seo_description" field.
func SeoDescriptionGTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGTE(FieldSeoDescription, v))
}

// SeoDescriptionLT applies the LT predicate on the "seo_description" field.
func SeoDescriptionLT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLT(FieldSeoDescription, v))
}

// SeoDescriptionLTE applies the LTE predicate on the "seo_description" field.
func SeoDescriptionLTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLTE(FieldSeoDescription, v))
}

// SeoDescriptionContains applies the Contains predicate on the "seo_description" field.
func SeoDescriptionContains(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContains(FieldSeoDescription, v))
}

// SeoDescriptionHasPrefix applies the HasPrefix predicate on the "seo_description" field.
func SeoDescriptionHasPrefix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasPrefix(FieldSeoDescription, v))
}

// SeoDescriptionHasSuffix applies the HasSuffix predicate on the "seo_description" field.
func SeoDescriptionHasSuffix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasSuffix(FieldSeoDescription, v))
}

// SeoDescriptionIsNil applies the IsNil predicate on the "seo_description" field.
func SeoDescriptionIsNil() predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIsNull(FieldSeoDescription))
}

// SeoDescriptionNotNil applies the NotNil predicate on the "seo_description" field.
func SeoDescriptionNotNil() predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotNull(FieldSeoDescription))
}

// SeoDescriptionEqualFold applies the EqualFold predicate on the "seo_description" field.
func SeoDescriptionEqualFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEqualFold(FieldSeoDescription, v))
}

// SeoDescriptionContainsFold applies the ContainsFold predicate on the "seo_description" field.
func SeoDescriptionContainsFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContainsFold(FieldSeoDescription, v))
}

// TranslationStatusEQ applies the EQ predicate on the "translation_status" field.
func TranslationStatusEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldTranslationStatus, v))
}

// TranslationStatusNEQ applies the NEQ predicate on the "translation_status" field.
func TranslationStatusNEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNEQ(FieldTranslationStatus, v))
}

// TranslationStatusIn applies the In predicate on the "translation_status" field.
func TranslationStatusIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIn(FieldTranslationStatus, vs...))
}

// TranslationStatusNotIn applies the NotIn predicate on the "translation_status" field.
func TranslationStatusNotIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotIn(FieldTranslationStatus, vs...))
}

// TranslationStatusGT applies the GT predicate on the "translation_status" field.
func TranslationStatusGT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGT(FieldTranslationStatus, v))
}

// TranslationStatusGTE applies the GTE predicate on the "translation_status" field.
func TranslationStatusGTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGTE(FieldTranslationStatus, v))
}

// TranslationStatusLT applies the LT predicate on the "translation_status" field.
func TranslationStatusLT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLT(FieldTranslationStatus, v))
}

// TranslationStatusLTE applies the LTE predicate on the "translation_status" field.
func TranslationStatusLTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLTE(FieldTranslationStatus, v))
}

// TranslationStatusContains applies the Contains predicate on the "translation_status" field.
func TranslationStatusContains(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContains(FieldTranslationStatus, v))
}

// TranslationStatusHasPrefix applies the HasPrefix predicate on the "translation_status" field.
func TranslationStatusHasPrefix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasPrefix(FieldTranslationStatus, v))
}

// TranslationStatusHasSuffix applies the HasSuffix predicate on the "translation_status" field.
func TranslationStatusHasSuffix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasSuffix(FieldTranslationStatus, v))
}

// TranslationStatusEqualFold applies the EqualFold predicate on the "translation_status" field.
func TranslationStatusEqualFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEqualFold(FieldTranslationStatus, v))
}

// TranslationStatusContainsFold applies the ContainsFold predicate on the "translation_status" field.
func TranslationStatusContainsFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContainsFold(FieldTranslationStatus, v))
}

// TranslationProviderEQ applies the EQ predicate on the "translation_provider" field.
func TranslationProviderEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldTranslationProvider, v))
}

// TranslationProviderNEQ applies the NEQ predicate on the "translation_provider" field.
func TranslationProviderNEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNEQ(FieldTranslationProvider, v))
}

// TranslationProviderIn applies the In predicate on the "translation_provider" field.
func TranslationProviderIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIn(FieldTranslationProvider, vs...))
}

// TranslationProviderNotIn applies the NotIn predicate on the "translation_provider" field.
func TranslationProviderNotIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotIn(FieldTranslationProvider, vs...))
}

// TranslationProviderGT applies the GT predicate on the "translation_provider" field.
func TranslationProviderGT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGT(FieldTranslationProvider, v))
}

// TranslationProviderGTE applies the GTE predicate on the "translation_provider" field.
func TranslationProviderGTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGTE(FieldTranslationProvider, v))
}

// TranslationProviderLT applies the LT predicate on the "translation_provider" field.
func TranslationProviderLT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLT(FieldTranslationProvider, v))
}

// TranslationProviderLTE applies the LTE predicate on the "translation_provider" field.
func TranslationProviderLTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLTE(FieldTranslationProvider, v))
}

// TranslationProviderContains applies the Contains predicate on the "translation_provider" field.
func TranslationProviderContains(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContains(FieldTranslationProvider, v))
}

// TranslationProviderHasPrefix applies the HasPrefix predicate on the "translation_provider" field.
func TranslationProviderHasPrefix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasPrefix(FieldTranslationProvider, v))
}

// TranslationProviderHasSuffix applies the HasSuffix predicate on the "translation_provider" field.
func TranslationProviderHasSuffix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasSuffix(FieldTranslationProvider, v))
}

// TranslationProviderIsNil applies the IsNil predicate on the "translation_provider" field.
func TranslationProviderIsNil() predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIsNull(FieldTranslationProvider))
}

// TranslationProviderNotNil applies the NotNil predicate on the "translation_provider" field.
func TranslationProviderNotNil() predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotNull(FieldTranslationProvider))
}

// TranslationProviderEqualFold applies the EqualFold predicate on the "translation_provider" field.
func TranslationProviderEqualFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEqualFold(FieldTranslationProvider, v))
}

// TranslationProviderContainsFold applies the ContainsFold predicate on the "translation_provider" field.
func TranslationProviderContainsFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContainsFold(FieldTranslationProvider, v))
}

// TranslatedFromLocaleEQ applies the EQ predicate on the "translated_from_locale" field.
func TranslatedFromLocaleEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldTranslatedFromLocale, v))
}

// TranslatedFromLocaleNEQ applies the NEQ predicate on the "translated_from_locale" field.
func TranslatedFromLocaleNEQ(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNEQ(FieldTranslatedFromLocale, v))
}

// TranslatedFromLocaleIn applies the In predicate on the "translated_from_locale" field.
func TranslatedFromLocaleIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIn(FieldTranslatedFromLocale, vs...))
}

// TranslatedFromLocaleNotIn applies the NotIn predicate on the "translated_from_locale" field.
func TranslatedFromLocaleNotIn(vs ...string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotIn(FieldTranslatedFromLocale, vs...))
}

// TranslatedFromLocaleGT applies the GT predicate on the "translated_from_locale" field.
func TranslatedFromLocaleGT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGT(FieldTranslatedFromLocale, v))
}

// TranslatedFromLocaleGTE applies the GTE predicate on the "translated_from_locale" field.
func TranslatedFromLocaleGTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGTE(FieldTranslatedFromLocale, v))
}

// TranslatedFromLocaleLT applies the LT predicate on the "translated_from_locale" field.
func TranslatedFromLocaleLT(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLT(FieldTranslatedFromLocale, v))
}

// TranslatedFromLocaleLTE applies the LTE predicate on the "translated_from_locale" field.
func TranslatedFromLocaleLTE(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLTE(FieldTranslatedFromLocale, v))
}

// TranslatedFromLocaleContains applies the Contains predicate on the "translated_from_locale" field.
func TranslatedFromLocaleContains(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContains(FieldTranslatedFromLocale, v))
}

// TranslatedFromLocaleHasPrefix applies the HasPrefix predicate on the "translated_from_locale" field.
func TranslatedFromLocaleHasPrefix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasPrefix(FieldTranslatedFromLocale, v))
}

// TranslatedFromLocaleHasSuffix applies the HasSuffix predicate on the "translated_from_locale" field.
func TranslatedFromLocaleHasSuffix(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldHasSuffix(FieldTranslatedFromLocale, v))
}

// TranslatedFromLocaleIsNil applies the IsNil predicate on the "translated_from_locale" field.
func TranslatedFromLocaleIsNil() predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIsNull(FieldTranslatedFromLocale))
}

// TranslatedFromLocaleNotNil applies the NotNil predicate on the "translated_from_locale" field.
func TranslatedFromLocaleNotNil() predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotNull(FieldTranslatedFromLocale))
}

// TranslatedFromLocaleEqualFold applies the EqualFold predicate on the "translated_from_locale" field.
func TranslatedFromLocaleEqualFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEqualFold(FieldTranslatedFromLocale, v))
}

// TranslatedFromLocaleContainsFold applies the ContainsFold predicate on the "translated_from_locale" field.
func TranslatedFromLocaleContainsFold(v string) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldContainsFold(FieldTranslatedFromLocale, v))
}

// LastTranslatedAtEQ applies the EQ predicate on the "last_translated_at" field.
func LastTranslatedAtEQ(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldLastTranslatedAt, v))
}

// LastTranslatedAtNEQ applies the NEQ predicate on the "last_translated_at" field.
func LastTranslatedAtNEQ(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNEQ(FieldLastTranslatedAt, v))
}

// LastTranslatedAtIn applies the In predicate on the "last_translated_at" field.
func LastTranslatedAtIn(vs ...time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIn(FieldLastTranslatedAt, vs...))
}

// LastTranslatedAtNotIn applies the NotIn predicate on the "last_translated_at" field.
func LastTranslatedAtNotIn(vs ...time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotIn(FieldLastTranslatedAt, vs...))
}

// LastTranslatedAtGT applies the GT predicate on the "last_translated_at" field.
func LastTranslatedAtGT(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGT(FieldLastTranslatedAt, v))
}

// LastTranslatedAtGTE applies the GTE predicate on the "last_translated_at" field.
func LastTranslatedAtGTE(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGTE(FieldLastTranslatedAt, v))
}

// LastTranslatedAtLT applies the LT predicate on the "last_translated_at" field.
func LastTranslatedAtLT(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLT(FieldLastTranslatedAt, v))
}

// LastTranslatedAtLTE applies the LTE predicate on the "last_translated_at" field.
func LastTranslatedAtLTE(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLTE(FieldLastTranslatedAt, v))
}

// LastTranslatedAtIsNil applies the IsNil predicate on the "last_translated_at" field.
func LastTranslatedAtIsNil() predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIsNull(FieldLastTranslatedAt))
}

// LastTranslatedAtNotNil applies the NotNil predicate on the "last_translated_at" field.
func LastTranslatedAtNotNil() predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotNull(FieldLastTranslatedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasNewsPost applies the HasEdge predicate on the "news_post" edge.
func HasNewsPost() predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, NewsPostTable, NewsPostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNewsPostWith applies the HasEdge predicate on the "news_post" edge with a given conditions (other predicates).
func HasNewsPostWith(preds ...predicate.NewsPost) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(func(s *sql.Selector) {
		step := newNewsPostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NewsPostTranslation) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NewsPostTranslation) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NewsPostTranslation) predicate.NewsPostTranslation {
	return predicate.NewsPostTranslation(sql.NotPredicates(p))
}
