// Code generated by ent, DO NOT EDIT.

package promotionrelation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the promotionrelation type in the database.
	Label = "promotion_relation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAgentUserID holds the string denoting the agent_user_id field in the database.
	FieldAgentUserID = "agent_user_id"
	// FieldDistributorUserID holds the string denoting the distributor_user_id field in the database.
	FieldDistributorUserID = "distributor_user_id"
	// FieldDirectParentUserID holds the string denoting the direct_parent_user_id field in the database.
	FieldDirectParentUserID = "direct_parent_user_id"
	// FieldDirectParentRole holds the string denoting the direct_parent_role field in the database.
	FieldDirectParentRole = "direct_parent_role"
	// FieldBindingSource holds the string denoting the binding_source field in the database.
	FieldBindingSource = "binding_source"
	// FieldIsLocked holds the string denoting the is_locked field in the database.
	FieldIsLocked = "is_locked"
	// FieldBoundAt holds the string denoting the bound_at field in the database.
	FieldBoundAt = "bound_at"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeAgentUser holds the string denoting the agent_user edge name in mutations.
	EdgeAgentUser = "agent_user"
	// EdgeDistributorUser holds the string denoting the distributor_user edge name in mutations.
	EdgeDistributorUser = "distributor_user"
	// EdgeDirectParentUser holds the string denoting the direct_parent_user edge name in mutations.
	EdgeDirectParentUser = "direct_parent_user"
	// Table holds the table name of the promotionrelation in the database.
	Table = "promotion_relations"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "promotion_relations"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// AgentUserTable is the table that holds the agent_user relation/edge.
	AgentUserTable = "promotion_relations"
	// AgentUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AgentUserInverseTable = "users"
	// AgentUserColumn is the table column denoting the agent_user relation/edge.
	AgentUserColumn = "agent_user_id"
	// DistributorUserTable is the table that holds the distributor_user relation/edge.
	DistributorUserTable = "promotion_relations"
	// DistributorUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	DistributorUserInverseTable = "users"
	// DistributorUserColumn is the table column denoting the distributor_user relation/edge.
	DistributorUserColumn = "distributor_user_id"
	// DirectParentUserTable is the table that holds the direct_parent_user relation/edge.
	DirectParentUserTable = "promotion_relations"
	// DirectParentUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	DirectParentUserInverseTable = "users"
	// DirectParentUserColumn is the table column denoting the direct_parent_user relation/edge.
	DirectParentUserColumn = "direct_parent_user_id"
)

// Columns holds all SQL columns for promotionrelation fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldAgentUserID,
	FieldDistributorUserID,
	FieldDirectParentUserID,
	FieldDirectParentRole,
	FieldBindingSource,
	FieldIsLocked,
	FieldBoundAt,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDirectParentRole holds the default value on creation for the "direct_parent_role" field.
	DefaultDirectParentRole string
	// DirectParentRoleValidator is a validator for the "direct_parent_role" field. It is called by the builders before save.
	DirectParentRoleValidator func(string) error
	// DefaultBindingSource holds the default value on creation for the "binding_source" field.
	DefaultBindingSource string
	// BindingSourceValidator is a validator for the "binding_source" field. It is called by the builders before save.
	BindingSourceValidator func(string) error
	// DefaultIsLocked holds the default value on creation for the "is_locked" field.
	DefaultIsLocked bool
	// DefaultBoundAt holds the default value on creation for the "bound_at" field.
	DefaultBoundAt func() time.Time
)

// OrderOption defines the ordering options for the PromotionRelation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAgentUserID orders the results by the agent_user_id field.
func ByAgentUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentUserID, opts...).ToFunc()
}

// ByDistributorUserID orders the results by the distributor_user_id field.
func ByDistributorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDistributorUserID, opts...).ToFunc()
}

// ByDirectParentUserID orders the results by the direct_parent_user_id field.
func ByDirectParentUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirectParentUserID, opts...).ToFunc()
}

// ByDirectParentRole orders the results by the direct_parent_role field.
func ByDirectParentRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirectParentRole, opts...).ToFunc()
}

// ByBindingSource orders the results by the binding_source field.
func ByBindingSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBindingSource, opts...).ToFunc()
}

// ByIsLocked orders the results by the is_locked field.
func ByIsLocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsLocked, opts...).ToFunc()
}

// ByBoundAt orders the results by the bound_at field.
func ByBoundAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBoundAt, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByAgentUserField orders the results by agent_user field.
func ByAgentUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAgentUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByDistributorUserField orders the results by distributor_user field.
func ByDistributorUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDistributorUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByDirectParentUserField orders the results by direct_parent_user field.
func ByDirectParentUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDirectParentUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
func newAgentUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AgentUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AgentUserTable, AgentUserColumn),
	)
}
func newDistributorUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DistributorUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, DistributorUserTable, DistributorUserColumn),
	)
}
func newDirectParentUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DirectParentUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, DirectParentUserTable, DirectParentUserColumn),
	)
}
