// Code generated by ent, DO NOT EDIT.

package commissionrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the commissionrule type in the database.
	Label = "commission_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCalcMode holds the string denoting the calc_mode field in the database.
	FieldCalcMode = "calc_mode"
	// FieldChannelPartnerTargetRate holds the string denoting the channel_partner_target_rate field in the database.
	FieldChannelPartnerTargetRate = "channel_partner_target_rate"
	// FieldAgentTargetRate holds the string denoting the agent_target_rate field in the database.
	FieldAgentTargetRate = "agent_target_rate"
	// FieldDistributorTargetRate holds the string denoting the distributor_target_rate field in the database.
	FieldDistributorTargetRate = "distributor_target_rate"
	// FieldFreezeHours holds the string denoting the freeze_hours field in the database.
	FieldFreezeHours = "freeze_hours"
	// FieldSettlementMode holds the string denoting the settlement_mode field in the database.
	FieldSettlementMode = "settlement_mode"
	// FieldScopeType holds the string denoting the scope_type field in the database.
	FieldScopeType = "scope_type"
	// FieldScopeID holds the string denoting the scope_id field in the database.
	FieldScopeID = "scope_id"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldEffectiveAt holds the string denoting the effective_at field in the database.
	FieldEffectiveAt = "effective_at"
	// FieldExpiredAt holds the string denoting the expired_at field in the database.
	FieldExpiredAt = "expired_at"
	// FieldConfigJSON holds the string denoting the config_json field in the database.
	FieldConfigJSON = "config_json"
	// Table holds the table name of the commissionrule in the database.
	Table = "commission_rules"
)

// Columns holds all SQL columns for commissionrule fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldStatus,
	FieldCalcMode,
	FieldChannelPartnerTargetRate,
	FieldAgentTargetRate,
	FieldDistributorTargetRate,
	FieldFreezeHours,
	FieldSettlementMode,
	FieldScopeType,
	FieldScopeID,
	FieldPriority,
	FieldEffectiveAt,
	FieldExpiredAt,
	FieldConfigJSON,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCalcMode holds the default value on creation for the "calc_mode" field.
	DefaultCalcMode string
	// CalcModeValidator is a validator for the "calc_mode" field. It is called by the builders before save.
	CalcModeValidator func(string) error
	// DefaultChannelPartnerTargetRate holds the default value on creation for the "channel_partner_target_rate" field.
	DefaultChannelPartnerTargetRate float64
	// DefaultAgentTargetRate holds the default value on creation for the "agent_target_rate" field.
	DefaultAgentTargetRate float64
	// DefaultDistributorTargetRate holds the default value on creation for the "distributor_target_rate" field.
	DefaultDistributorTargetRate float64
	// DefaultFreezeHours holds the default value on creation for the "freeze_hours" field.
	DefaultFreezeHours int
	// DefaultSettlementMode holds the default value on creation for the "settlement_mode" field.
	DefaultSettlementMode string
	// SettlementModeValidator is a validator for the "settlement_mode" field. It is called by the builders before save.
	SettlementModeValidator func(string) error
	// DefaultScopeType holds the default value on creation for the "scope_type" field.
	DefaultScopeType string
	// ScopeTypeValidator is a validator for the "scope_type" field. It is called by the builders before save.
	ScopeTypeValidator func(string) error
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
)

// OrderOption defines the ordering options for the CommissionRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCalcMode orders the results by the calc_mode field.
func ByCalcMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCalcMode, opts...).ToFunc()
}

// ByChannelPartnerTargetRate orders the results by the channel_partner_target_rate field.
func ByChannelPartnerTargetRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelPartnerTargetRate, opts...).ToFunc()
}

// ByAgentTargetRate orders the results by the agent_target_rate field.
func ByAgentTargetRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentTargetRate, opts...).ToFunc()
}

// ByDistributorTargetRate orders the results by the distributor_target_rate field.
func ByDistributorTargetRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDistributorTargetRate, opts...).ToFunc()
}

// ByFreezeHours orders the results by the freeze_hours field.
func ByFreezeHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFreezeHours, opts...).ToFunc()
}

// BySettlementMode orders the results by the settlement_mode field.
func BySettlementMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementMode, opts...).ToFunc()
}

// ByScopeType orders the results by the scope_type field.
func ByScopeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeType, opts...).ToFunc()
}

// ByScopeID orders the results by the scope_id field.
func ByScopeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeID, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByEffectiveAt orders the results by the effective_at field.
func ByEffectiveAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveAt, opts...).ToFunc()
}

// ByExpiredAt orders the results by the expired_at field.
func ByExpiredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiredAt, opts...).ToFunc()
}
