// Code generated by ent, DO NOT EDIT.

package commissionrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/dlxyz/SubioHub/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldName, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldStatus, v))
}

// CalcMode applies equality check predicate on the "calc_mode" field. It's identical to CalcModeEQ.
func CalcMode(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldCalcMode, v))
}

// AgentTargetRate applies equality check predicate on the "agent_target_rate" field. It's identical to AgentTargetRateEQ.
func AgentTargetRate(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldAgentTargetRate, v))
}

// DistributorTargetRate applies equality check predicate on the "distributor_target_rate" field. It's identical to DistributorTargetRateEQ.
func DistributorTargetRate(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldDistributorTargetRate, v))
}

// FreezeHours applies equality check predicate on the "freeze_hours" field. It's identical to FreezeHoursEQ.
func FreezeHours(v int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldFreezeHours, v))
}

// SettlementMode applies equality check predicate on the "settlement_mode" field. It's identical to SettlementModeEQ.
func SettlementMode(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldSettlementMode, v))
}

// ScopeType applies equality check predicate on the "scope_type" field. It's identical to ScopeTypeEQ.
func ScopeType(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldScopeType, v))
}

// ScopeID applies equality check predicate on the "scope_id" field. It's identical to ScopeIDEQ.
func ScopeID(v int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldScopeID, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldPriority, v))
}

// EffectiveAt applies equality check predicate on the "effective_at" field. It's identical to EffectiveAtEQ.
func EffectiveAt(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldEffectiveAt, v))
}

// ExpiredAt applies equality check predicate on the "expired_at" field. It's identical to ExpiredAtEQ.
func ExpiredAt(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldExpiredAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldContainsFold(FieldStatus, v))
}

// CalcModeEQ applies the EQ predicate on the "calc_mode" field.
func CalcModeEQ(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldCalcMode, v))
}

// CalcModeNEQ applies the NEQ predicate on the "calc_mode" field.
func CalcModeNEQ(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldCalcMode, v))
}

// CalcModeIn applies the In predicate on the "calc_mode" field.
func CalcModeIn(vs ...string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldCalcMode, vs...))
}

// CalcModeNotIn applies the NotIn predicate on the "calc_mode" field.
func CalcModeNotIn(vs ...string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldCalcMode, vs...))
}

// CalcModeGT applies the GT predicate on the "calc_mode" field.
func CalcModeGT(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldCalcMode, v))
}

// CalcModeGTE applies the GTE predicate on the "calc_mode" field.
func CalcModeGTE(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldCalcMode, v))
}

// CalcModeLT applies the LT predicate on the "calc_mode" field.
func CalcModeLT(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldCalcMode, v))
}

// CalcModeLTE applies the LTE predicate on the "calc_mode" field.
func CalcModeLTE(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldCalcMode, v))
}

// CalcModeContains applies the Contains predicate on the "calc_mode" field.
func CalcModeContains(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldContains(FieldCalcMode, v))
}

// CalcModeHasPrefix applies the HasPrefix predicate on the "calc_mode" field.
func CalcModeHasPrefix(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldHasPrefix(FieldCalcMode, v))
}

// CalcModeHasSuffix applies the HasSuffix predicate on the "calc_mode" field.
func CalcModeHasSuffix(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldHasSuffix(FieldCalcMode, v))
}

// CalcModeEqualFold applies the EqualFold predicate on the "calc_mode" field.
func CalcModeEqualFold(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEqualFold(FieldCalcMode, v))
}

// CalcModeContainsFold applies the ContainsFold predicate on the "calc_mode" field.
func CalcModeContainsFold(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldContainsFold(FieldCalcMode, v))
}

// AgentTargetRateEQ applies the EQ predicate on the "agent_target_rate" field.
func AgentTargetRateEQ(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldAgentTargetRate, v))
}

// AgentTargetRateNEQ applies the NEQ predicate on the "agent_target_rate" field.
func AgentTargetRateNEQ(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldAgentTargetRate, v))
}

// AgentTargetRateIn applies the In predicate on the "agent_target_rate" field.
func AgentTargetRateIn(vs ...float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldAgentTargetRate, vs...))
}

// AgentTargetRateNotIn applies the NotIn predicate on the "agent_target_rate" field.
func AgentTargetRateNotIn(vs ...float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldAgentTargetRate, vs...))
}

// AgentTargetRateGT applies the GT predicate on the "agent_target_rate" field.
func AgentTargetRateGT(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldAgentTargetRate, v))
}

// AgentTargetRateGTE applies the GTE predicate on the "agent_target_rate" field.
func AgentTargetRateGTE(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldAgentTargetRate, v))
}

// AgentTargetRateLT applies the LT predicate on the "agent_target_rate" field.
func AgentTargetRateLT(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldAgentTargetRate, v))
}

// AgentTargetRateLTE applies the LTE predicate on the "agent_target_rate" field.
func AgentTargetRateLTE(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldAgentTargetRate, v))
}

// DistributorTargetRateEQ applies the EQ predicate on the "distributor_target_rate" field.
func DistributorTargetRateEQ(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldDistributorTargetRate, v))
}

// DistributorTargetRateNEQ applies the NEQ predicate on the "distributor_target_rate" field.
func DistributorTargetRateNEQ(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldDistributorTargetRate, v))
}

// DistributorTargetRateIn applies the In predicate on the "distributor_target_rate" field.
func DistributorTargetRateIn(vs ...float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldDistributorTargetRate, vs...))
}

// DistributorTargetRateNotIn applies the NotIn predicate on the "distributor_target_rate" field.
func DistributorTargetRateNotIn(vs ...float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldDistributorTargetRate, vs...))
}

// DistributorTargetRateGT applies the GT predicate on the "distributor_target_rate" field.
func DistributorTargetRateGT(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldDistributorTargetRate, v))
}

// DistributorTargetRateGTE applies the GTE predicate on the "distributor_target_rate" field.
func DistributorTargetRateGTE(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldDistributorTargetRate, v))
}

// DistributorTargetRateLT applies the LT predicate on the "distributor_target_rate" field.
func DistributorTargetRateLT(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldDistributorTargetRate, v))
}

// DistributorTargetRateLTE applies the LTE predicate on the "distributor_target_rate" field.
func DistributorTargetRateLTE(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldDistributorTargetRate, v))
}

// FreezeHoursEQ applies the EQ predicate on the "freeze_hours" field.
func FreezeHoursEQ(v int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldFreezeHours, v))
}

// FreezeHoursNEQ applies the NEQ predicate on the "freeze_hours" field.
func FreezeHoursNEQ(v int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldFreezeHours, v))
}

// FreezeHoursIn applies the In predicate on the "freeze_hours" field.
func FreezeHoursIn(vs ...int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldFreezeHours, vs...))
}

// FreezeHoursNotIn applies the NotIn predicate on the "freeze_hours" field.
func FreezeHoursNotIn(vs ...int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldFreezeHours, vs...))
}

// FreezeHoursGT applies the GT predicate on the "freeze_hours" field.
func FreezeHoursGT(v int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldFreezeHours, v))
}

// FreezeHoursGTE applies the GTE predicate on the "freeze_hours" field.
func FreezeHoursGTE(v int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldFreezeHours, v))
}

// FreezeHoursLT applies the LT predicate on the "freeze_hours" field.
func FreezeHoursLT(v int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldFreezeHours, v))
}

// FreezeHoursLTE applies the LTE predicate on the "freeze_hours" field.
func FreezeHoursLTE(v int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldFreezeHours, v))
}

// SettlementModeEQ applies the EQ predicate on the "settlement_mode" field.
func SettlementModeEQ(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldSettlementMode, v))
}

// SettlementModeNEQ applies the NEQ predicate on the "settlement_mode" field.
func SettlementModeNEQ(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldSettlementMode, v))
}

// SettlementModeIn applies the In predicate on the "settlement_mode" field.
func SettlementModeIn(vs ...string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldSettlementMode, vs...))
}

// SettlementModeNotIn applies the NotIn predicate on the "settlement_mode" field.
func SettlementModeNotIn(vs ...string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldSettlementMode, vs...))
}

// SettlementModeGT applies the GT predicate on the "settlement_mode" field.
func SettlementModeGT(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldSettlementMode, v))
}

// SettlementModeGTE applies the GTE predicate on the "settlement_mode" field.
func SettlementModeGTE(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldSettlementMode, v))
}

// SettlementModeLT applies the LT predicate on the "settlement_mode" field.
func SettlementModeLT(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldSettlementMode, v))
}

// SettlementModeLTE applies the LTE predicate on the "settlement_mode" field.
func SettlementModeLTE(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldSettlementMode, v))
}

// SettlementModeContains applies the Contains predicate on the "settlement_mode" field.
func SettlementModeContains(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldContains(FieldSettlementMode, v))
}

// SettlementModeHasPrefix applies the HasPrefix predicate on the "settlement_mode" field.
func SettlementModeHasPrefix(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldHasPrefix(FieldSettlementMode, v))
}

// SettlementModeHasSuffix applies the HasSuffix predicate on the "settlement_mode" field.
func SettlementModeHasSuffix(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldHasSuffix(FieldSettlementMode, v))
}

// SettlementModeEqualFold applies the EqualFold predicate on the "settlement_mode" field.
func SettlementModeEqualFold(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEqualFold(FieldSettlementMode, v))
}

// SettlementModeContainsFold applies the ContainsFold predicate on the "settlement_mode" field.
func SettlementModeContainsFold(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldContainsFold(FieldSettlementMode, v))
}

// ScopeTypeEQ applies the EQ predicate on the "scope_type" field.
func ScopeTypeEQ(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldScopeType, v))
}

// ScopeTypeNEQ applies the NEQ predicate on the "scope_type" field.
func ScopeTypeNEQ(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldScopeType, v))
}

// ScopeTypeIn applies the In predicate on the "scope_type" field.
func ScopeTypeIn(vs ...string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldScopeType, vs...))
}

// ScopeTypeNotIn applies the NotIn predicate on the "scope_type" field.
func ScopeTypeNotIn(vs ...string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldScopeType, vs...))
}

// ScopeTypeGT applies the GT predicate on the "scope_type" field.
func ScopeTypeGT(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldScopeType, v))
}

// ScopeTypeGTE applies the GTE predicate on the "scope_type" field.
func ScopeTypeGTE(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldScopeType, v))
}

// ScopeTypeLT applies the LT predicate on the "scope_type" field.
func ScopeTypeLT(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldScopeType, v))
}

// ScopeTypeLTE applies the LTE predicate on the "scope_type" field.
func ScopeTypeLTE(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldScopeType, v))
}

// ScopeTypeContains applies the Contains predicate on the "scope_type" field.
func ScopeTypeContains(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldContains(FieldScopeType, v))
}

// ScopeTypeHasPrefix applies the HasPrefix predicate on the "scope_type" field.
func ScopeTypeHasPrefix(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldHasPrefix(FieldScopeType, v))
}

// ScopeTypeHasSuffix applies the HasSuffix predicate on the "scope_type" field.
func ScopeTypeHasSuffix(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldHasSuffix(FieldScopeType, v))
}

// ScopeTypeEqualFold applies the EqualFold predicate on the "scope_type" field.
func ScopeTypeEqualFold(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEqualFold(FieldScopeType, v))
}

// ScopeTypeContainsFold applies the ContainsFold predicate on the "scope_type" field.
func ScopeTypeContainsFold(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldContainsFold(FieldScopeType, v))
}

// ScopeIDEQ applies the EQ predicate on the "scope_id" field.
func ScopeIDEQ(v int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldScopeID, v))
}

// ScopeIDNEQ applies the NEQ predicate on the "scope_id" field.
func ScopeIDNEQ(v int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldScopeID, v))
}

// ScopeIDIn applies the In predicate on the "scope_id" field.
func ScopeIDIn(vs ...int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldScopeID, vs...))
}

// ScopeIDNotIn applies the NotIn predicate on the "scope_id" field.
func ScopeIDNotIn(vs ...int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldScopeID, vs...))
}

// ScopeIDGT applies the GT predicate on the "scope_id" field.
func ScopeIDGT(v int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldScopeID, v))
}

// ScopeIDGTE applies the GTE predicate on the "scope_id" field.
func ScopeIDGTE(v int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldScopeID, v))
}

// ScopeIDLT applies the LT predicate on the "scope_id" field.
func ScopeIDLT(v int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldScopeID, v))
}

// ScopeIDLTE applies the LTE predicate on the "scope_id" field.
func ScopeIDLTE(v int64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldScopeID, v))
}

// ScopeIDIsNil applies the IsNil predicate on the "scope_id" field.
func ScopeIDIsNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIsNull(FieldScopeID))
}

// ScopeIDNotNil applies the NotNil predicate on the "scope_id" field.
func ScopeIDNotNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotNull(FieldScopeID))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldPriority, v))
}

// EffectiveAtEQ applies the EQ predicate on the "effective_at" field.
func EffectiveAtEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldEffectiveAt, v))
}

// EffectiveAtNEQ applies the NEQ predicate on the "effective_at" field.
func EffectiveAtNEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldEffectiveAt, v))
}

// EffectiveAtIn applies the In predicate on the "effective_at" field.
func EffectiveAtIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldEffectiveAt, vs...))
}

// EffectiveAtNotIn applies the NotIn predicate on the "effective_at" field.
func EffectiveAtNotIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldEffectiveAt, vs...))
}

// EffectiveAtGT applies the GT predicate on the "effective_at" field.
func EffectiveAtGT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldEffectiveAt, v))
}

// EffectiveAtGTE applies the GTE predicate on the "effective_at" field.
func EffectiveAtGTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldEffectiveAt, v))
}

// EffectiveAtLT applies the LT predicate on the "effective_at" field.
func EffectiveAtLT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldEffectiveAt, v))
}

// EffectiveAtLTE applies the LTE predicate on the "effective_at" field.
func EffectiveAtLTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldEffectiveAt, v))
}

// EffectiveAtIsNil applies the IsNil predicate on the "effective_at" field.
func EffectiveAtIsNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIsNull(FieldEffectiveAt))
}

// EffectiveAtNotNil applies the NotNil predicate on the "effective_at" field.
func EffectiveAtNotNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotNull(FieldEffectiveAt))
}

// ExpiredAtEQ applies the EQ predicate on the "expired_at" field.
func ExpiredAtEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldExpiredAt, v))
}

// ExpiredAtNEQ applies the NEQ predicate on the "expired_at" field.
func ExpiredAtNEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldExpiredAt, v))
}

// ExpiredAtIn applies the In predicate on the "expired_at" field.
func ExpiredAtIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldExpiredAt, vs...))
}

// ExpiredAtNotIn applies the NotIn predicate on the "expired_at" field.
func ExpiredAtNotIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldExpiredAt, vs...))
}

// ExpiredAtGT applies the GT predicate on the "expired_at" field.
func ExpiredAtGT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldExpiredAt, v))
}

// ExpiredAtGTE applies the GTE predicate on the "expired_at" field.
func ExpiredAtGTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldExpiredAt, v))
}

// ExpiredAtLT applies the LT predicate on the "expired_at" field.
func ExpiredAtLT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldExpiredAt, v))
}

// ExpiredAtLTE applies the LTE predicate on the "expired_at" field.
func ExpiredAtLTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldExpiredAt, v))
}

// ExpiredAtIsNil applies the IsNil predicate on the "expired_at" field.
func ExpiredAtIsNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIsNull(FieldExpiredAt))
}

// ExpiredAtNotNil applies the NotNil predicate on the "expired_at" field.
func ExpiredAtNotNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotNull(FieldExpiredAt))
}

// ConfigJSONIsNil applies the IsNil predicate on the "config_json" field.
func ConfigJSONIsNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIsNull(FieldConfigJSON))
}

// ConfigJSONNotNil applies the NotNil predicate on the "config_json" field.
func ConfigJSONNotNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotNull(FieldConfigJSON))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CommissionRule) predicate.CommissionRule {
	return predicate.CommissionRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CommissionRule) predicate.CommissionRule {
	return predicate.CommissionRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CommissionRule) predicate.CommissionRule {
	return predicate.CommissionRule(sql.NotPredicates(p))
}
