// Code generated by ent, DO NOT EDIT.

package commissionsplitlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the commissionsplitlog type in the database.
	Label = "commission_split_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldConsumerUserID holds the string denoting the consumer_user_id field in the database.
	FieldConsumerUserID = "consumer_user_id"
	// FieldBeneficiaryUserID holds the string denoting the beneficiary_user_id field in the database.
	FieldBeneficiaryUserID = "beneficiary_user_id"
	// FieldBeneficiaryRole holds the string denoting the beneficiary_role field in the database.
	FieldBeneficiaryRole = "beneficiary_role"
	// FieldChannelPartnerUserID holds the string denoting the channel_partner_user_id field in the database.
	FieldChannelPartnerUserID = "channel_partner_user_id"
	// FieldAgentUserID holds the string denoting the agent_user_id field in the database.
	FieldAgentUserID = "agent_user_id"
	// FieldDistributorUserID holds the string denoting the distributor_user_id field in the database.
	FieldDistributorUserID = "distributor_user_id"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldCalcMode holds the string denoting the calc_mode field in the database.
	FieldCalcMode = "calc_mode"
	// FieldBaseAmount holds the string denoting the base_amount field in the database.
	FieldBaseAmount = "base_amount"
	// FieldTargetRate holds the string denoting the target_rate field in the database.
	FieldTargetRate = "target_rate"
	// FieldParentRate holds the string denoting the parent_rate field in the database.
	FieldParentRate = "parent_rate"
	// FieldCommissionAmount holds the string denoting the commission_amount field in the database.
	FieldCommissionAmount = "commission_amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRuleID holds the string denoting the rule_id field in the database.
	FieldRuleID = "rule_id"
	// FieldSettledAt holds the string denoting the settled_at field in the database.
	FieldSettledAt = "settled_at"
	// FieldRelationSnapshot holds the string denoting the relation_snapshot field in the database.
	FieldRelationSnapshot = "relation_snapshot"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// EdgePaymentOrder holds the string denoting the payment_order edge name in mutations.
	EdgePaymentOrder = "payment_order"
	// EdgeConsumerUser holds the string denoting the consumer_user edge name in mutations.
	EdgeConsumerUser = "consumer_user"
	// EdgeBeneficiaryUser holds the string denoting the beneficiary_user edge name in mutations.
	EdgeBeneficiaryUser = "beneficiary_user"
	// EdgeChannelPartnerUser holds the string denoting the channel_partner_user edge name in mutations.
	EdgeChannelPartnerUser = "channel_partner_user"
	// EdgeAgentUser holds the string denoting the agent_user edge name in mutations.
	EdgeAgentUser = "agent_user"
	// EdgeDistributorUser holds the string denoting the distributor_user edge name in mutations.
	EdgeDistributorUser = "distributor_user"
	// EdgeCommissionRule holds the string denoting the commission_rule edge name in mutations.
	EdgeCommissionRule = "commission_rule"
	// Table holds the table name of the commissionsplitlog in the database.
	Table = "commission_split_logs"
	// PaymentOrderTable is the table that holds the payment_order relation/edge.
	PaymentOrderTable = "commission_split_logs"
	// PaymentOrderInverseTable is the table name for the PaymentOrder entity.
	// It exists in this package in order to avoid circular dependency with the "paymentorder" package.
	PaymentOrderInverseTable = "payment_orders"
	// PaymentOrderColumn is the table column denoting the payment_order relation/edge.
	PaymentOrderColumn = "order_id"
	// ConsumerUserTable is the table that holds the consumer_user relation/edge.
	ConsumerUserTable = "commission_split_logs"
	// ConsumerUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ConsumerUserInverseTable = "users"
	// ConsumerUserColumn is the table column denoting the consumer_user relation/edge.
	ConsumerUserColumn = "consumer_user_id"
	// BeneficiaryUserTable is the table that holds the beneficiary_user relation/edge.
	BeneficiaryUserTable = "commission_split_logs"
	// BeneficiaryUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	BeneficiaryUserInverseTable = "users"
	// BeneficiaryUserColumn is the table column denoting the beneficiary_user relation/edge.
	BeneficiaryUserColumn = "beneficiary_user_id"
	// ChannelPartnerUserTable is the table that holds the channel_partner_user relation/edge.
	ChannelPartnerUserTable = "commission_split_logs"
	// ChannelPartnerUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ChannelPartnerUserInverseTable = "users"
	// ChannelPartnerUserColumn is the table column denoting the channel_partner_user relation/edge.
	ChannelPartnerUserColumn = "channel_partner_user_id"
	// AgentUserTable is the table that holds the agent_user relation/edge.
	AgentUserTable = "commission_split_logs"
	// AgentUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AgentUserInverseTable = "users"
	// AgentUserColumn is the table column denoting the agent_user relation/edge.
	AgentUserColumn = "agent_user_id"
	// DistributorUserTable is the table that holds the distributor_user relation/edge.
	DistributorUserTable = "commission_split_logs"
	// DistributorUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	DistributorUserInverseTable = "users"
	// DistributorUserColumn is the table column denoting the distributor_user relation/edge.
	DistributorUserColumn = "distributor_user_id"
	// CommissionRuleTable is the table that holds the commission_rule relation/edge.
	CommissionRuleTable = "commission_split_logs"
	// CommissionRuleInverseTable is the table name for the CommissionRule entity.
	// It exists in this package in order to avoid circular dependency with the "commissionrule" package.
	CommissionRuleInverseTable = "commission_rules"
	// CommissionRuleColumn is the table column denoting the commission_rule relation/edge.
	CommissionRuleColumn = "rule_id"
)

// Columns holds all SQL columns for commissionsplitlog fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldOrderID,
	FieldConsumerUserID,
	FieldBeneficiaryUserID,
	FieldBeneficiaryRole,
	FieldChannelPartnerUserID,
	FieldAgentUserID,
	FieldDistributorUserID,
	FieldLevel,
	FieldCalcMode,
	FieldBaseAmount,
	FieldTargetRate,
	FieldParentRate,
	FieldCommissionAmount,
	FieldStatus,
	FieldRuleID,
	FieldSettledAt,
	FieldRelationSnapshot,
	FieldRemark,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultBeneficiaryRole holds the default value on creation for the "beneficiary_role" field.
	DefaultBeneficiaryRole string
	// BeneficiaryRoleValidator is a validator for the "beneficiary_role" field. It is called by the builders before save.
	BeneficiaryRoleValidator func(string) error
	// DefaultLevel holds the default value on creation for the "level" field.
	DefaultLevel int
	// DefaultCalcMode holds the default value on creation for the "calc_mode" field.
	DefaultCalcMode string
	// CalcModeValidator is a validator for the "calc_mode" field. It is called by the builders before save.
	CalcModeValidator func(string) error
	// DefaultBaseAmount holds the default value on creation for the "base_amount" field.
	DefaultBaseAmount float64
	// DefaultTargetRate holds the default value on creation for the "target_rate" field.
	DefaultTargetRate float64
	// DefaultParentRate holds the default value on creation for the "parent_rate" field.
	DefaultParentRate float64
	// DefaultCommissionAmount holds the default value on creation for the "commission_amount" field.
	DefaultCommissionAmount float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the CommissionSplitLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByConsumerUserID orders the results by the consumer_user_id field.
func ByConsumerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsumerUserID, opts...).ToFunc()
}

// ByBeneficiaryUserID orders the results by the beneficiary_user_id field.
func ByBeneficiaryUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBeneficiaryUserID, opts...).ToFunc()
}

// ByBeneficiaryRole orders the results by the beneficiary_role field.
func ByBeneficiaryRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBeneficiaryRole, opts...).ToFunc()
}

// ByChannelPartnerUserID orders the results by the channel_partner_user_id field.
func ByChannelPartnerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelPartnerUserID, opts...).ToFunc()
}

// ByAgentUserID orders the results by the agent_user_id field.
func ByAgentUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentUserID, opts...).ToFunc()
}

// ByDistributorUserID orders the results by the distributor_user_id field.
func ByDistributorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDistributorUserID, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByCalcMode orders the results by the calc_mode field.
func ByCalcMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCalcMode, opts...).ToFunc()
}

// ByBaseAmount orders the results by the base_amount field.
func ByBaseAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseAmount, opts...).ToFunc()
}

// ByTargetRate orders the results by the target_rate field.
func ByTargetRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetRate, opts...).ToFunc()
}

// ByParentRate orders the results by the parent_rate field.
func ByParentRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentRate, opts...).ToFunc()
}

// ByCommissionAmount orders the results by the commission_amount field.
func ByCommissionAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommissionAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRuleID orders the results by the rule_id field.
func ByRuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleID, opts...).ToFunc()
}

// BySettledAt orders the results by the settled_at field.
func BySettledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAt, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByPaymentOrderField orders the results by payment_order field.
func ByPaymentOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPaymentOrderStep(), sql.OrderByField(field, opts...))
	}
}

// ByConsumerUserField orders the results by consumer_user field.
func ByConsumerUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConsumerUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByBeneficiaryUserField orders the results by beneficiary_user field.
func ByBeneficiaryUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBeneficiaryUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByChannelPartnerUserField orders the results by channel_partner_user field.
func ByChannelPartnerUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelPartnerUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByAgentUserField orders the results by agent_user field.
func ByAgentUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAgentUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByDistributorUserField orders the results by distributor_user field.
func ByDistributorUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDistributorUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByCommissionRuleField orders the results by commission_rule field.
func ByCommissionRuleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommissionRuleStep(), sql.OrderByField(field, opts...))
	}
}
func newPaymentOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PaymentOrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, PaymentOrderTable, PaymentOrderColumn),
	)
}
func newConsumerUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConsumerUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ConsumerUserTable, ConsumerUserColumn),
	)
}
func newBeneficiaryUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BeneficiaryUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, BeneficiaryUserTable, BeneficiaryUserColumn),
	)
}
func newChannelPartnerUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelPartnerUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ChannelPartnerUserTable, ChannelPartnerUserColumn),
	)
}
func newAgentUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AgentUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AgentUserTable, AgentUserColumn),
	)
}
func newDistributorUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DistributorUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, DistributorUserTable, DistributorUserColumn),
	)
}
func newCommissionRuleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommissionRuleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, CommissionRuleTable, CommissionRuleColumn),
	)
}
